#!/usr/bin/env python3
"""
Regenerate wiki pages from docs/ into a checked-out wiki clone, per the
curated mapping in .github/wiki-publish-map.json.

Usage: publish_wiki.py <repo_root> <wiki_clone_dir>

Every page this script writes carries a GENERATED_MARKER header. On each
run, any existing wiki page that carries that marker but is no longer in
the mapping gets deleted (its source was removed from the mapping) — but
a page WITHOUT the marker (hand-maintained, e.g. a legacy page pending
migration) is never touched or deleted, regardless of whether it's listed
in the mapping's legacy_pages. That distinction (marker present = we own
it) is the only thing that makes "regenerate" safe to run unattended.

LINK REWRITING (the part docs-lint.py can never check): docs/ uses its own
[[file.md]] wiki-link convention, meant to render as plain text on GitHub's
normal file view. GitHub WIKI pages give `[[...]]` a second, DIFFERENT
meaning — native wiki auto-linking, keyed on the literal bracketed text as
a page name. Copying a docs/ page's body verbatim into a wiki page lets
GitHub's wiki engine reinterpret our own convention out from under us:
`[[../troubleshooting.md]]` auto-links to a page literally named
"../troubleshooting.md" (mangled into a dead slug), and `[[printing-tags.md]]`
auto-links to "printing-tags.md" (the raw docs/ filename's casing), not the
actual published page name "Printing-Tags". Both bugs are invisible to
docs_lint.py, which only checks that a link resolves inside the docs/ tree
itself — the wiki's own `[[...]]` reinterpretation is a second transform
downstream of that check, and this is the only place it can be caught.

Every internal link (both `[[wiki]]` and markdown `[text](path)` styles) is
therefore resolved against its SOURCE file's real repo path, then mapped
through wiki-publish-map.json: a target that's itself a published page
becomes a same-wiki link using its REAL page name (never the raw docs/
filename); a target that exists in the repo but isn't published becomes an
absolute GitHub blob URL (never a guessed wiki slug); a target that resolves
to neither a wiki page nor a real repo file is a hard error - the publish
FAILS rather than shipping a page with a link nobody can follow.

Exits 0 whether or not anything changed; the calling workflow decides
whether to commit based on `git status --porcelain` in the wiki dir.
"""

import json
import re
import sys
from pathlib import Path

GENERATED_MARKER = "<!-- GENERATED PAGE"
GITHUB_BLOB_BASE = "https://github.com/ProxyPrints/ProxyPrints.github.io/blob/master/"

# Order matters: fence/inline must be tried before the link alternatives so
# code content is never rewritten - both this repo's own [[wiki-link]] prose
# convention AND real markdown links appear verbatim as ILLUSTRATIVE EXAMPLES
# inside backticks in some docs (e.g. documentation-process.md explaining
# this very system) and must not be touched.
LINK_TOKEN_RE = re.compile(
    r"(?P<fence>```.*?```)"
    r"|(?P<inline>`[^`\n]+`)"
    r"|\[\[(?P<wikilink>[^\]]+)\]\]"
    r"|(?<!!)\[(?P<mdtext>[^\]]*)\]\((?P<mdpath>[^)]+)\)",
    re.DOTALL,
)


def generated_header(source_path: str) -> str:
    return (
        f"{GENERATED_MARKER} — do not edit directly.\n"
        f"     Source: `{source_path}` in the main repo — edit there; this\n"
        f"     page regenerates automatically on the next docs/ change.\n"
        f"     Generated by .github/workflows/docs-wiki-publish.yml -->\n\n"
    )


def load_mapping(repo_root: Path) -> dict:
    with open(repo_root / ".github" / "wiki-publish-map.json") as f:
        return json.load(f)


def build_repo_to_wiki_map(mapping: dict) -> dict:
    # page.get("wiki"), not page["wiki"]: a page can be site-only (per
    # docs/proposals/proposal-i-docs-as-site-source.md's targets schema
    # extension) with no "wiki" key at all - skip those rather than
    # KeyError on every publish once one exists in the mapping.
    return {page["source"]: page["wiki"] for group in mapping["groups"] for page in group["pages"] if page.get("wiki")}


def resolve_repo_relative(repo_root: Path, source_rel: str, target: str) -> str | None:
    """
    Resolve a link target string against source_rel's own directory. Returns
    a repo-relative posix path, or None if target isn't a local-file
    reference at all (external URL, bare anchor, mailto:).
    """
    if target.startswith(("http://", "https://", "mailto:")) or target.startswith("#"):
        return None
    path_part = target.split("#", 1)[0]
    if not path_part:
        return None
    source_dir = (repo_root / source_rel).parent
    resolved = (source_dir / path_part).resolve()
    try:
        rel = resolved.relative_to(repo_root.resolve())
    except ValueError:
        return None  # escaped the repo root somehow - treat as external, not our problem
    return rel.as_posix()


def rewrite_link(
    repo_root: Path, source_rel: str, target: str, repo_to_wiki: dict, display_text: str | None
) -> tuple[str | None, str | None]:
    """Returns (new_markdown_link, error_message) - exactly one is non-None, unless
    target wasn't a local path at all (both None - caller leaves the original text)."""
    resolved_rel = resolve_repo_relative(repo_root, source_rel, target)
    if resolved_rel is None:
        return None, None

    wiki_name = repo_to_wiki.get(resolved_rel)
    if wiki_name:
        text = display_text or wiki_name
        return f"[{text}]({wiki_name})", None

    if not (repo_root / resolved_rel).is_file():
        return None, (
            f"in {source_rel}: link to `{target}` resolves to `{resolved_rel}`, which is "
            f"neither a published wiki page nor a real file in the repo"
        )

    text = display_text or resolved_rel.rsplit("/", 1)[-1]
    return f"[{text}]({GITHUB_BLOB_BASE}{resolved_rel})", None


def transform_links(repo_root: Path, source_rel: str, text: str, repo_to_wiki: dict, errors: list[str]) -> str:
    def repl(m: re.Match) -> str:
        if m.group("fence") is not None or m.group("inline") is not None:
            return m.group(0)

        if m.group("wikilink") is not None:
            target = m.group("wikilink")
            if not (target.endswith(".md") or "/" in target):
                return m.group(0)  # e.g. [[routes]] - a literal TOML table, not a doc link
            new_link, err = rewrite_link(repo_root, source_rel, target, repo_to_wiki, display_text=None)
            if err:
                errors.append(err)
                return m.group(0)
            return new_link or m.group(0)

        # markdown link
        mdtext, mdpath = m.group("mdtext"), m.group("mdpath")
        new_link, err = rewrite_link(repo_root, source_rel, mdpath, repo_to_wiki, display_text=mdtext or None)
        if err:
            errors.append(err)
            return m.group(0)
        return new_link if new_link else m.group(0)

    return LINK_TOKEN_RE.sub(repl, text)


def write_page(
    wiki_dir: Path,
    wiki_name: str,
    source_path: Path,
    source_rel: str,
    repo_root: Path,
    repo_to_wiki: dict,
    errors: list[str],
) -> None:
    body = source_path.read_text()
    transformed = transform_links(repo_root, source_rel, body, repo_to_wiki, errors)
    content = generated_header(source_rel) + transformed
    (wiki_dir / f"{wiki_name}.md").write_text(content)


def write_pointer_page(wiki_dir: Path, wiki_name: str, points_to: str, note: str) -> None:
    """
    A stub page whose content has been folded into another page (e.g. a
    once-standalone page superseded by a real docs/ write-up) — kept at
    its existing name/URL (no wiki redirects exist) rather than deleted,
    so nothing that links to it breaks.
    """
    content = (
        generated_header(".github/wiki-publish-map.json (pointer_pages)")
        + f"# {wiki_name.replace('-', ' ')}\n\n"
        + f"This content now lives on the [{points_to}]({points_to}) page. {note}\n"
    )
    (wiki_dir / f"{wiki_name}.md").write_text(content)


def build_home_and_sidebar(
    repo_root: Path, wiki_dir: Path, mapping: dict, repo_to_wiki: dict, errors: list[str]
) -> None:
    intro_raw = (repo_root / "docs" / "wiki-home-intro.md").read_text().rstrip() + "\n"
    intro = transform_links(repo_root, "docs/wiki-home-intro.md", intro_raw, repo_to_wiki, errors)

    home_lines = [
        generated_header("docs/wiki-home-intro.md + .github/wiki-publish-map.json"),
        intro,
        "\n## Wiki contents\n",
    ]
    sidebar_lines = [generated_header(".github/wiki-publish-map.json"), "**[Home](Home)**\n"]

    for group in mapping["groups"]:
        home_lines.append(f"\n### {group['title']}\n")
        sidebar_lines.append(f"\n_{group['title']}_\n")
        for page in group["pages"]:
            home_lines.append(f"- [{page['wiki']}]({page['wiki']})")
            sidebar_lines.append(f"- [{page['wiki']}]({page['wiki']})")

    pointers = mapping.get("pointer_pages", [])
    if pointers:
        home_lines.append("\n### Folded into other pages\n")
        sidebar_lines.append("\n_Folded into other pages_\n")
        for page in pointers:
            home_lines.append(f"- [{page['wiki']}]({page['wiki']}) → see [{page['points_to']}]({page['points_to']})")
            sidebar_lines.append(f"- [{page['wiki']}]({page['wiki']})")

    legacy = mapping.get("legacy_pages", [])
    if legacy:
        home_lines.append(
            "\n## Not yet migrated\n\n"
            "These pages predate the generated system and aren't sourced "
            "from docs/ yet — pending an owner decision (migrate into "
            "docs/, or keep hand-maintained). Not touched by this "
            "workflow.\n"
        )
        sidebar_lines.append("\n_Not yet migrated_\n")
        for page in legacy:
            home_lines.append(f"- [{page['wiki']}]({page['wiki']}) — {page['note']}")
            sidebar_lines.append(f"- [{page['wiki']}]({page['wiki']})")

    (wiki_dir / "Home.md").write_text("\n".join(home_lines) + "\n")
    (wiki_dir / "_Sidebar.md").write_text("\n".join(sidebar_lines) + "\n")


def main() -> int:
    repo_root = Path(sys.argv[1]).resolve()
    wiki_dir = Path(sys.argv[2]).resolve()

    mapping = load_mapping(repo_root)
    repo_to_wiki = build_repo_to_wiki_map(mapping)
    errors: list[str] = []

    managed_names = set()
    for group in mapping["groups"]:
        for page in group["pages"]:
            source_rel = page["source"]
            source_path = repo_root / source_rel
            if not source_path.is_file():
                print(f"::error::wiki-publish-map.json references missing source {source_rel}")
                return 1
            if not page.get("wiki"):
                # site-only page (see build_repo_to_wiki_map) - nothing for
                # this script to publish.
                continue
            write_page(wiki_dir, page["wiki"], source_path, source_rel, repo_root, repo_to_wiki, errors)
            managed_names.add(page["wiki"])
            print(f"wrote {page['wiki']}.md <- {source_rel}")

    for pointer in mapping.get("pointer_pages", []):
        if pointer["points_to"] not in managed_names:
            print(
                f"::error::pointer_pages entry {pointer['wiki']!r} points to "
                f"{pointer['points_to']!r}, which isn't a real published page"
            )
            return 1
        write_pointer_page(wiki_dir, pointer["wiki"], pointer["points_to"], pointer["note"])
        managed_names.add(pointer["wiki"])
        print(f"wrote {pointer['wiki']}.md (pointer -> {pointer['points_to']})")

    build_home_and_sidebar(repo_root, wiki_dir, mapping, repo_to_wiki, errors)
    managed_names.update({"Home", "_Sidebar"})

    if errors:
        for err in errors:
            print(f"::error::{err}")
        print(
            f"\n{len(errors)} link-resolution error(s) - failing the publish. "
            f"docs_lint.py cannot catch this class of break (it only checks links "
            f"resolve inside docs/ itself, not what they become after this script's "
            f"wiki-name/blob-URL rewrite) - fix the source link or add the missing "
            f"page to wiki-publish-map.json."
        )
        return 1

    # Prune generated pages whose source left the mapping. Never touch a
    # page that doesn't carry our marker — that's hand-maintained content.
    for existing in wiki_dir.glob("*.md"):
        name = existing.stem
        if name in managed_names:
            continue
        text = existing.read_text()
        if text.startswith(GENERATED_MARKER):
            print(f"removing {existing.name} (generated, no longer in mapping)")
            existing.unlink()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
