#!/usr/bin/env python3
"""
Regenerate wiki pages from docs/ into a checked-out wiki clone, per the
curated mapping in .github/wiki-publish-map.json.

Usage: publish_wiki.py <repo_root> <wiki_clone_dir>

Every page this script writes carries a GENERATED_MARKER header. On each
run, any existing wiki page that carries that marker but is no longer in
the mapping gets deleted (its source was removed from the mapping) — but
a page WITHOUT the marker (hand-maintained, e.g. a legacy page pending
migration) is never touched or deleted, regardless of whether it's listed
in the mapping's legacy_pages. That distinction (marker present = we own
it) is the only thing that makes "regenerate" safe to run unattended.

Exits 0 whether or not anything changed; the calling workflow decides
whether to commit based on `git status --porcelain` in the wiki dir.
"""
import json
import sys
from pathlib import Path

GENERATED_MARKER = "<!-- GENERATED PAGE"


def generated_header(source_path: str) -> str:
    return (
        f"{GENERATED_MARKER} — do not edit directly.\n"
        f"     Source: `{source_path}` in the main repo — edit there; this\n"
        f"     page regenerates automatically on the next docs/ change.\n"
        f"     Generated by .github/workflows/docs-wiki-publish.yml -->\n\n"
    )


def load_mapping(repo_root: Path) -> dict:
    with open(repo_root / ".github" / "wiki-publish-map.json") as f:
        return json.load(f)


def write_page(wiki_dir: Path, wiki_name: str, source_path: Path, source_rel: str) -> None:
    body = source_path.read_text()
    content = generated_header(source_rel) + body
    (wiki_dir / f"{wiki_name}.md").write_text(content)


def build_home_and_sidebar(repo_root: Path, wiki_dir: Path, mapping: dict) -> None:
    intro = (repo_root / "docs" / "wiki-home-intro.md").read_text().rstrip() + "\n"

    home_lines = [generated_header("docs/wiki-home-intro.md + .github/wiki-publish-map.json"), intro, "\n## Wiki contents\n"]
    sidebar_lines = [generated_header(".github/wiki-publish-map.json"), "**[Home](Home)**\n"]

    for group in mapping["groups"]:
        home_lines.append(f"\n### {group['title']}\n")
        sidebar_lines.append(f"\n_{group['title']}_\n")
        for page in group["pages"]:
            home_lines.append(f"- [{page['wiki']}]({page['wiki']})")
            sidebar_lines.append(f"- [{page['wiki']}]({page['wiki']})")

    legacy = mapping.get("legacy_pages", [])
    if legacy:
        home_lines.append(
            "\n## Not yet migrated\n\n"
            "These pages predate the generated system and aren't sourced "
            "from docs/ yet — pending an owner decision (migrate into "
            "docs/, or keep hand-maintained). Not touched by this "
            "workflow.\n"
        )
        sidebar_lines.append("\n_Not yet migrated_\n")
        for page in legacy:
            home_lines.append(f"- [{page['wiki']}]({page['wiki']}) — {page['note']}")
            sidebar_lines.append(f"- [{page['wiki']}]({page['wiki']})")

    (wiki_dir / "Home.md").write_text("\n".join(home_lines) + "\n")
    (wiki_dir / "_Sidebar.md").write_text("\n".join(sidebar_lines) + "\n")


def main() -> int:
    repo_root = Path(sys.argv[1]).resolve()
    wiki_dir = Path(sys.argv[2]).resolve()

    mapping = load_mapping(repo_root)

    managed_names = set()
    for group in mapping["groups"]:
        for page in group["pages"]:
            source_rel = page["source"]
            source_path = repo_root / source_rel
            if not source_path.is_file():
                print(f"::error::wiki-publish-map.json references missing source {source_rel}")
                return 1
            write_page(wiki_dir, page["wiki"], source_path, source_rel)
            managed_names.add(page["wiki"])
            print(f"wrote {page['wiki']}.md <- {source_rel}")

    build_home_and_sidebar(repo_root, wiki_dir, mapping)
    managed_names.update({"Home", "_Sidebar"})

    # Prune generated pages whose source left the mapping. Never touch a
    # page that doesn't carry our marker — that's hand-maintained content.
    for existing in wiki_dir.glob("*.md"):
        name = existing.stem
        if name in managed_names:
            continue
        text = existing.read_text()
        if text.startswith(GENERATED_MARKER):
            print(f"removing {existing.name} (generated, no longer in mapping)")
            existing.unlink()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
