# Generated by Django 4.2.30 on 2026-07-12 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0049_card_canonical_artist"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalPrintingMetadata",
            fields=[
                (
                    "canonical_card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="printing_metadata",
                        serialize=False,
                        to="cardpicker.canonicalcard",
                    ),
                ),
                ("full_art", models.BooleanField(default=False)),
                ("border_color", models.CharField(blank=True, max_length=20)),
                ("frame", models.CharField(blank=True, max_length=10)),
                ("frame_effects", models.JSONField(blank=True, default=list)),
                ("promo_types", models.JSONField(blank=True, default=list)),
                ("edhrec_rank", models.IntegerField(blank=True, null=True)),
                ("printings_count", models.IntegerField(default=0)),
                ("released_at", models.DateField(blank=True, null=True)),
                ("lang", models.CharField(default="en", max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="CardPrintingTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_no_match", models.BooleanField(default=False)),
                ("session_key", models.CharField(max_length=40)),
                (
                    "source",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin"), ("ai", "AI")], default="user", max_length=10
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="printing_tags", to="cardpicker.card"
                    ),
                ),
                (
                    "printing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="cardpicker.canonicalcard",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cardprintingtag",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("is_no_match", False), ("printing__isnull", False)),
                    models.Q(("is_no_match", True), ("printing__isnull", True)),
                    _connector="OR",
                ),
                name="cardprintingtag_printing_xor_no_match",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardprintingtag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_no_match", False)),
                fields=("card", "printing", "session_key"),
                name="cardprintingtag_unique_printing_vote",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardprintingtag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_no_match", True)),
                fields=("card", "session_key"),
                name="cardprintingtag_unique_no_match_vote",
            ),
        ),
    ]
