# Generated by Django 4.2.30 on 2026-07-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0050_canonicalprintingmetadata_cardprintingtag_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cardprintingtag",
            name="cardprintingtag_unique_printing_vote",
        ),
        migrations.RemoveConstraint(
            model_name="cardprintingtag",
            name="cardprintingtag_unique_no_match_vote",
        ),
        migrations.RenameField(
            model_name="cardprintingtag",
            old_name="session_key",
            new_name="anonymous_id",
        ),
        migrations.AddField(
            model_name="card",
            name="printing_tag_status",
            field=models.CharField(
                choices=[("unresolved", "Unresolved"), ("resolved", "Resolved"), ("no_match", "No Match")],
                db_index=True,
                default="unresolved",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="cardprintingtag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_no_match", False)),
                fields=("card", "printing", "anonymous_id"),
                name="cardprintingtag_unique_printing_vote",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardprintingtag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_no_match", True)),
                fields=("card", "anonymous_id"),
                name="cardprintingtag_unique_no_match_vote",
            ),
        ),
    ]
