# Generated by Django 4.2.30 on 2026-07-12 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0052_tagaliassuggestion_card_expansion_hint"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="artist_vote_status",
            field=models.CharField(
                choices=[("unresolved", "Unresolved"), ("resolved", "Resolved"), ("unknown", "Unknown")],
                db_index=True,
                default="unresolved",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="inferred_canonical_artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cardpicker.canonicalartist",
            ),
        ),
        migrations.CreateModel(
            name="CardTagVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("anonymous_id", models.CharField(max_length=40)),
                (
                    "source",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin"), ("ai", "AI")], default="user", max_length=10
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("polarity", models.SmallIntegerField(choices=[(1, "Apply"), (-1, "Not applicable")])),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tag_votes", to="cardpicker.card"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="cardpicker.tag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CardArtistVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("anonymous_id", models.CharField(max_length=40)),
                (
                    "source",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin"), ("ai", "AI")], default="user", max_length=10
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_unknown", models.BooleanField(default=False)),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="cardpicker.canonicalartist",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="artist_votes", to="cardpicker.card"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cardtagvote",
            constraint=models.UniqueConstraint(fields=("card", "tag", "anonymous_id"), name="cardtagvote_unique_vote"),
        ),
        migrations.AddConstraint(
            model_name="cardartistvote",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("artist__isnull", False), ("is_unknown", False)),
                    models.Q(("artist__isnull", True), ("is_unknown", True)),
                    _connector="OR",
                ),
                name="cardartistvote_artist_xor_unknown",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardartistvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_unknown", False)),
                fields=("card", "artist", "anonymous_id"),
                name="cardartistvote_unique_artist_vote",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardartistvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_unknown", True)),
                fields=("card", "anonymous_id"),
                name="cardartistvote_unique_unknown_vote",
            ),
        ),
    ]
