# Generated by Django 4.2.30 on 2026-07-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0053_card_artist_vote_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardartistvote",
            name="peer",
            field=models.CharField(
                blank=True, help_text="Federation peer name; set only when source='federated'", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="cardprintingtag",
            name="peer",
            field=models.CharField(
                blank=True, help_text="Federation peer name; set only when source='federated'", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="cardtagvote",
            name="peer",
            field=models.CharField(
                blank=True, help_text="Federation peer name; set only when source='federated'", max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cardartistvote",
            name="source",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin"), ("ai", "AI"), ("federated", "Federated")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cardprintingtag",
            name="source",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin"), ("ai", "AI"), ("federated", "Federated")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cardtagvote",
            name="source",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin"), ("ai", "AI"), ("federated", "Federated")],
                default="user",
                max_length=10,
            ),
        ),
    ]
