# Generated by Django 4.2.30 on 2026-07-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0054_cardartistvote_peer_cardprintingtag_peer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="tag_vote_statuses",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="card",
            name="artist_vote_status",
            field=models.CharField(
                choices=[
                    ("unresolved", "Unresolved"),
                    ("resolved", "Resolved"),
                    ("unknown", "Unknown"),
                    ("contested", "Contested"),
                ],
                db_index=True,
                default="unresolved",
                max_length=10,
            ),
        ),
    ]
