# Generated by Django 4.2.30 on 2026-07-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0055_card_tag_vote_statuses_alter_card_artist_vote_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Presentation only — freely editable. `name` is the immutable machine key used by votes, tag_vote_statuses, Card.tags, and federation; NEVER rename a Tag after creation.",
                max_length=200,
                null=True,
            ),
        ),
    ]
