# Generated by Django 4.2.30 on 2026-07-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0057_cardartistvote_user_cardprintingtag_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="moderation_class",
            field=models.CharField(
                choices=[("standard", "Standard"), ("sensitive", "Sensitive")], default="standard", max_length=10
            ),
        ),
    ]
