# Generated by Django 4.2.30 on 2026-07-15 13:31

from django.db import migrations, models

# VoteSource.AI -> DEDUCTION/OCR split (see cardpicker/models.py's VoteSource docstring). Every
# existing production source="ai" row predates the split and comes exclusively from
# deductive_backfill.py's own production run (pure logical inference, zero image inspection) -
# so the one-time backfill is unconditionally "ai" -> "deduction", never "ocr" (nothing wrote
# "ai" rows via image inspection before this split existed). Covers all three
# AbstractWeightedVote subclasses since they share this field, even though CardArtistVote/
# CardTagVote have no known "ai" rows in production - harmless no-ops if so.
_AI_SOURCE = "ai"
_DEDUCTION_SOURCE = "deduction"


def _backfill_ai_to_deduction(apps, schema_editor) -> None:  # type: ignore  # TODO: type this properly
    for model_name in ("CardArtistVote", "CardPrintingTag", "CardTagVote"):
        model = apps.get_model("cardpicker", model_name)
        model.objects.filter(source=_AI_SOURCE).update(source=_DEDUCTION_SOURCE)


def _revert_deduction_to_ai(apps, schema_editor) -> None:  # type: ignore  # TODO: type this properly
    # irreversible in general (an "ocr" row has no way back to being distinguished from a
    # pre-split "deduction"-turned-"ai" row), but the forward migration itself never produces
    # "ocr" rows from "ai" ones, so reversing only the rows this migration itself touched is
    # unambiguous and safe.
    for model_name in ("CardArtistVote", "CardPrintingTag", "CardTagVote"):
        model = apps.get_model("cardpicker", model_name)
        model.objects.filter(source=_DEDUCTION_SOURCE).update(source=_AI_SOURCE)


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0059_cardreport"),
    ]

    operations = [
        migrations.RunPython(_backfill_ai_to_deduction, _revert_deduction_to_ai),
        migrations.AlterField(
            model_name="cardartistvote",
            name="source",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("deduction", "Deduction"),
                    ("ocr", "OCR"),
                    ("federated", "Federated"),
                ],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cardprintingtag",
            name="source",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("deduction", "Deduction"),
                    ("ocr", "OCR"),
                    ("federated", "Federated"),
                ],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cardtagvote",
            name="source",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("deduction", "Deduction"),
                    ("ocr", "OCR"),
                    ("federated", "Federated"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
