# Generated by Django 4.2.30 on 2026-07-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0060_votesource_deduction_ocr_split"),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotRunLedger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.CharField(max_length=64, unique=True)),
                ("command", models.CharField(max_length=64)),
                ("dry_run", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("completed", "Completed"), ("failed", "Failed")],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("git_sha", models.CharField(blank=True, max_length=40, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("votes_written", models.IntegerField(blank=True, null=True)),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="cardartistvote",
            name="run_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="cardprintingtag",
            name="run_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="cardtagvote",
            name="run_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
