# Generated by Django 4.2.30 on 2026-07-16 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0062_card_content_phash"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardScanLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("anonymous_id", models.CharField(max_length=40)),
                ("run_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("skip_reason", models.CharField(max_length=64)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="scan_logs", to="cardpicker.card"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["card", "anonymous_id"], name="cardpicker__card_id_0c4b56_idx")],
            },
        ),
    ]
