# Generated by Django 4.2.30 on 2026-07-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0063_cardscanlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardartistvote",
            name="vote_surface",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="cardprintingtag",
            name="vote_surface",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="cardtagvote",
            name="vote_surface",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
