# Generated by Django 4.2.30 on 2026-07-18 20:28

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cardpicker", "0064_cardartistvote_vote_surface_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCryptoProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("salt", models.BinaryField()),
                ("kdf_iterations", models.PositiveIntegerField()),
                ("passphrase_wrapped_master_key", models.BinaryField()),
                ("passphrase_wrapped_master_key_nonce", models.BinaryField()),
                ("recovery_wrapped_master_key", models.BinaryField()),
                ("recovery_wrapped_master_key_nonce", models.BinaryField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_deck_crypto_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedDeck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("deck", "Deck"), ("snapshot", "Snapshot")], default="deck", max_length=20
                    ),
                ),
                ("ciphertext", models.BinaryField()),
                ("ciphertext_nonce", models.BinaryField()),
                ("wrapped_dek", models.BinaryField()),
                ("wrapped_dek_nonce", models.BinaryField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_decks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
