# Generated by Django 4.2.30 on 2026-07-19 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0065_usercryptoprofile_saveddeck"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandsAmbiguousResidue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.CharField(db_index=True, max_length=64)),
                ("artist_name", models.CharField(max_length=200)),
                ("candidate_pks", models.JSONField()),
                ("phash_distances", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lands_ambiguous_residue",
                        to="cardpicker.card",
                    ),
                ),
            ],
        ),
    ]
