# Generated by Django 4.2.30 on 2026-07-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0066_lands_ambiguous_residue"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalprintingmetadata",
            name="art_crop_url",
            field=models.CharField(blank=True, default=""),
        ),
    ]
