# Generated by Django 4.2.30 on 2026-07-19 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0067_canonicalprintingmetadata_art_crop_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content_hash", models.BigIntegerField(db_index=True)),
                ("extractor_versions", models.JSONField(blank=True, default=dict)),
                ("run_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("fetch_ok", models.BooleanField(blank=True, null=True)),
                ("fetch_error_class", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="image_evidence", to="cardpicker.card"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["card", "content_hash"], name="cardpicker__card_id_bd1736_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="imageevidence",
            constraint=models.UniqueConstraint(
                fields=("card", "content_hash"), name="unique_image_evidence_per_card_hash"
            ),
        ),
    ]
