# Generated by Django 4.2.30 on 2026-07-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0068_imageevidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageevidence",
            name="aspect_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="bleed_class",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
