# Generated by Django 4.2.30 on 2026-07-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0069_geometry_bleed_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageevidence",
            name="art_crop_px",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="artist_crop_px",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="collector_line_crop_px",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="layout_class",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
