# Generated by Django 4.2.30 on 2026-07-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0070_geometry_group_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageevidence",
            name="artist_ocr_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="artist_ocr_raw_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="collector_line_collector_number",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="collector_line_raw_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="collector_line_set_code",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="collector_line_word_boxes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="illus_anchor_fired",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
