# Generated by Django 4.2.30 on 2026-07-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0071_imageevidence_artist_ocr_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardscanlog",
            name="evidence_types_used",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cardscanlog",
            name="survivor_pks",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
