# Generated by Django 4.2.30 on 2026-07-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0072_cardscanlog_evidence_types_used_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageevidence",
            name="symbol_crop_px",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="symbol_phash",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
