# Generated by Django 4.2.30 on 2026-07-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0073_imageevidence_symbol_crop_px_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageevidence",
            name="legal_line_copyright_year",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="legal_line_crop_px",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="legal_line_proxy_marker_detected",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="legal_line_raw_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
