# Generated by Django 4.2.30 on 2026-07-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0074_legal_line_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageevidence",
            name="blur_variance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="color_mean_rgb",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="color_stddev_rgb",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="fetch_image_format",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="fetch_latency_ms",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="image_entropy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="image_is_truncated",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
