# Generated by Django 4.2.30 on 2026-07-20 22:46

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0075_visual_signal_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedDeckShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("ciphertext", models.BinaryField()),
                ("ciphertext_nonce", models.BinaryField()),
                ("wrapped_dek", models.BinaryField()),
                ("wrapped_dek_nonce", models.BinaryField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shares", to="cardpicker.saveddeck"
                    ),
                ),
            ],
        ),
    ]
