# Generated by Django 4.2.30 on 2026-07-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0076_saveddeckshare"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardartistvote",
            name="source",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("deduction", "Deduction"),
                    ("ocr", "OCR"),
                    ("federated", "Federated"),
                    ("implicit", "Implicit"),
                ],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cardprintingtag",
            name="source",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("deduction", "Deduction"),
                    ("ocr", "OCR"),
                    ("federated", "Federated"),
                    ("implicit", "Implicit"),
                ],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cardtagvote",
            name="source",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("deduction", "Deduction"),
                    ("ocr", "OCR"),
                    ("federated", "Federated"),
                    ("implicit", "Implicit"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
