# Generated by Django 4.2.30 on 2026-07-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0077_votesource_implicit"),
    ]

    operations = [
        migrations.AddField(
            model_name="pilotrunledger",
            name="counters",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
