# Generated by Django 4.2.30 on 2026-07-24 16:41

from django.db import migrations, models

import cardpicker.models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0078_pilotrunledger_counters"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvelopeTrip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "trip_id",
                    models.CharField(default=cardpicker.models._generate_envelope_trip_id, max_length=40, unique=True),
                ),
                (
                    "bar",
                    models.CharField(
                        choices=[
                            ("host_load", "Host load average"),
                            ("rss", "RSS per worker"),
                            ("fetch_failure_rate", "Fetch failure rate"),
                            ("google_lockout", "Google fetch lockout"),
                        ],
                        max_length=32,
                    ),
                ),
                ("detail", models.JSONField(blank=True, null=True)),
                ("run_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("tripped_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_note", models.TextField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["acknowledged_at", "tripped_at"], name="cardpicker__acknowl_b6f6ea_idx")
                ],
            },
        ),
    ]
