# Generated by Django 4.2.30 on 2026-07-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0080_questionfeedservedlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="StageEThrottleCounter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_key", models.PositiveSmallIntegerField(default=1, unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
                ("last_throttled_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
