# Generated by Django 4.2.30 on 2026-07-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0083_stageesweepcursor_keyed"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="md5_checksum",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
