# Generated by Django 4.2.30 on 2026-07-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0084_card_md5_checksum"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageevidence",
            name="md5_checksum",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="sha256_checksum",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="transferred",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="transferred_from_card_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
