# Generated by Django 4.2.30 on 2026-07-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0085_imageevidence_transfer_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageevidence",
            name="artbox_crop_px",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="artbox_frame_class",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="artbox_phash",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
