# Generated by Django 4.2.30 on 2026-07-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0094_warm_catalog_stats_hourly_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalprintingmetadata",
            name="face_illustrations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="canonicalprintingmetadata",
            index=models.Index(
                condition=models.Q(("face_illustrations", []), _negated=True),
                fields=["canonical_card"],
                name="cpm_face_illustrations_present",
            ),
        ),
    ]
