# Generated by Django 4.2.30 on 2026-07-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    # Renumbered 0096 -> 0098 and repointed off 0095. Two migrations called 0096 landed on master
    # independently (#568's `0096_card_scan_log_anon_skip_idx` and #570's freeze migration, which
    # #576 renumbered to `0097_freeze_deductive_backfill_zero_weight_cohort` to give the graph a
    # single leaf again). 0098 is the next free number after that chain, and depending on its leaf
    # is what keeps the graph linear rather than adding a third node hanging off 0095.
    dependencies = [
        ("cardpicker", "0097_freeze_deductive_backfill_zero_weight_cohort"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="illustration_vote_status",
            field=models.CharField(
                choices=[
                    ("unresolved", "Unresolved"),
                    ("resolved", "Resolved"),
                    ("unknown", "Unknown"),
                    ("contested", "Contested"),
                ],
                db_index=True,
                default="unresolved",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="inferred_illustration_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
