# Generated by Django 4.2.30 on 2026-08-05 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0101_delete_printingtagvote"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtboxPhashExemplar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("illustration_id", models.UUIDField(db_index=True)),
                ("artbox_phash", models.BigIntegerField(db_index=True)),
                (
                    "seed_kind",
                    models.CharField(
                        choices=[
                            ("human_resolution", "Human-backed printing resolution"),
                            ("join_key_machine", "High-confidence join-key vote"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_human_backed", models.BooleanField()),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("seed_group_key", models.CharField(db_index=True, max_length=128)),
                ("content_hash", models.BigIntegerField()),
                ("run_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artbox_phash_exemplar",
                        to="cardpicker.card",
                    ),
                ),
                (
                    "printing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artbox_phash_exemplars",
                        to="cardpicker.canonicalcard",
                    ),
                ),
                (
                    "source_vote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cardpicker.cardprintingtag",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="artboxphashexemplar",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("is_human_backed", True), ("seed_kind", "human_resolution")),
                    models.Q(("is_human_backed", False), ("seed_kind", "join_key_machine")),
                    _connector="OR",
                ),
                name="artboxphashexemplar_seed_kind_matches_human_backed",
            ),
        ),
    ]
