# Generated by Django 4.2.30 on 2026-07-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0101_delete_printingtagvote"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalFetchPace",
            fields=[
                ("destination", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("next_allowed_at", models.DateTimeField()),
                ("backoff_multiplier", models.FloatField(default=1.0)),
                ("clean_streak", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "global fetch pace",
                "verbose_name_plural": "global fetch paces",
            },
        ),
    ]
