# Generated by Django 4.2.30 on 2026-08-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0102_artbox_phash_exemplar"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalprintingmetadata",
            name="layout",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
