"""
Fixes the duplicate django-q2 `Schedule` rows that exist in production for the four
question-feed pool warmers (issue #727 / PR #752's `0105_question_feed_pools_schedule.py`).

WHAT ACTUALLY HAPPENED
----------------------
Production has EIGHT `django_q_schedule` rows for the four lane warmers - ids 6/7, 8/9, 10/11,
12/13, one extra row per lane, each pair's `next_run` stamped ~1ms apart. The 2026-08-06 deploy
wave booted two `migrate` runs concurrently (two containers running `docker/django/entrypoint.sh`
overlapping in the same window), and both ran 0105's `create_schedules` at the same instant.
`get_or_create` is NOT race-proof: each process's SELECT saw no row, so each INSERTed one - the
classic check-then-act window, closed only by a database-level uniqueness guarantee, which
`django_q.Schedule` does not ship (its `name` field has no unique constraint, verified against
the installed django-q2).

WHAT THIS MIGRATION DOES
------------------------
1. Dedupes: for every schedule NAME that has more than one row, keeps the earliest (lowest id)
   and deletes the rest. The duplicated members of each pair carry byte-identical
   `func`/`args`/`schedule_type`/`minutes` and `next_run` values ~1ms apart, so qcluster treats
   them identically and which one survives is immaterial - lowest id is the deterministic,
   reproducible choice.
2. Adds a `UNIQUE` constraint on `Schedule.name`, so the race above cannot recur: the second of
   two concurrent `get_or_create` calls now trips `IntegrityError` inside django-q's own
   get_or_create retry loop and re-reads the winner's row instead of inserting a duplicate. This
   also guards every other schedule-creating migration in the repo (0093/0094/0105 use
   `get_or_create`; `0048_auto_20260426_2140.py` was converted to `get_or_create` in the same
   PR, so the constraint can never turn a re-run into an unhandled `IntegrityError`).

WHY THE CONSTRAINT IS ADDED THROUGH `RunPython`, NOT `migrations.AddConstraint`
-------------------------------------------------------------------------------
`AddConstraint` resolves `model_name` against the MIGRATION's own app label (`cardpicker`), and
`django_q.Schedule` lives in the third-party `django_q` app - which we deliberately do not write
migrations into. `schema_editor.add_constraint` takes the model object directly, so the DDL is
generated by the same `UniqueConstraint.create_sql` machinery `AddConstraint` uses, but against
the state-rendered `django_q.Schedule` - correct for Postgres in production and SQLite in a
local sandbox, no vendor-frozen SQL (same philosophy as 0092's `createcachetable` invocation).

REVERSAL
--------
Reversible. Forward: dedupe first, then the constraint (order matters - the constraint must not
exist while duplicates still do). Backward: the constraint is dropped first, then the dedupe
reverses to a no-op (deleting the duplicates is not undone - it is a data fix, and reversing a
data fix by re-creating duplicate rows would re-introduce the bug; a `noop` reverse keeps a
rolled-back deploy from resurrecting doubled warm load).
"""

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

# Same literal in the forward and reverse paths; kept at module level so the two operations and
# the test module can all reference one name.
UNIQUE_CONSTRAINT_NAME = "django_q_schedule_name_uniq"


def dedupe_schedules(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """
    Collapse duplicate `django_q.Schedule` rows to one per name, keeping the earliest row
    (lowest id). Names with a single row are untouched. Idempotent: a second run finds no
    duplicates and deletes nothing.
    """
    Schedule = apps.get_model("django_q", "Schedule")
    for name in Schedule.objects.values_list("name", flat=True).distinct():
        duplicate_ids = list(Schedule.objects.filter(name=name).order_by("id").values_list("id", flat=True)[1:])
        if duplicate_ids:
            Schedule.objects.filter(pk__in=duplicate_ids).delete()


def add_name_unique_constraint(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """The database-level uniqueness guarantee `get_or_create` cannot provide on its own (see
    module docstring for the concurrency race that produced the production duplicates)."""
    Schedule = apps.get_model("django_q", "Schedule")
    schema_editor.add_constraint(
        Schedule,
        models.UniqueConstraint(fields=["name"], name=UNIQUE_CONSTRAINT_NAME),
    )


def remove_name_unique_constraint(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Schedule = apps.get_model("django_q", "Schedule")
    schema_editor.remove_constraint(
        Schedule,
        models.UniqueConstraint(fields=["name"], name=UNIQUE_CONSTRAINT_NAME),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0105_question_feed_pools_schedule"),
    ]

    operations = [
        migrations.RunPython(dedupe_schedules, migrations.RunPython.noop),
        migrations.RunPython(add_name_unique_constraint, remove_name_unique_constraint),
    ]
