# Generated by Django 4.2.30 on 2026-08-07 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0107_question_feed_pools_schedule_dedupe"),
    ]

    operations = [
        migrations.CreateModel(
            name="HiddenCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("anonymous_id", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="hidden_by", to="cardpicker.card"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="hiddencard",
            constraint=models.UniqueConstraint(fields=("card", "anonymous_id"), name="hiddencard_unique_hide"),
        ),
    ]
