# Generated by Django 4.2.30 on 2026-08-11 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cardpicker", "0108_hiddencard"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardIllustrationRejection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("anonymous_id", models.CharField(max_length=40)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("admin", "Admin"),
                            ("deduction", "Deduction"),
                            ("ocr", "OCR"),
                            ("federated", "Federated"),
                            ("implicit", "Implicit"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "peer",
                    models.CharField(
                        blank=True,
                        help_text="Federation peer name; set only when source='federated'",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("run_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("vote_surface", models.CharField(blank=True, max_length=64, null=True)),
                ("illustration_id", models.UUIDField(db_index=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="illustration_rejections",
                        to="cardpicker.card",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["card", "illustration_id"], name="cardillusrej_card_illus_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="cardillustrationrejection",
            constraint=models.UniqueConstraint(
                fields=("card", "anonymous_id", "illustration_id"), name="cardillustrationrejection_unique_vote"
            ),
        ),
    ]
