# Generated by Django 4.2.30 on 2026-08-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0111_cardprintingtag_evidence_types_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_call_bottom",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_call_left",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_call_right",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_call_top",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_frac_bottom",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_frac_left",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_frac_right",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_frac_top",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_verdict",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
