# Generated by Django 4.2.30 on 2026-08-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0115_question_feed_remaining_estimate_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalOracleCard",
            fields=[
                ("canonical_id", models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ("oracle_text", models.TextField(blank=True, default="")),
                ("cmc", models.FloatField(default=0)),
                ("colors", models.JSONField(blank=True, default=list)),
                ("color_identity", models.JSONField(blank=True, default=list)),
                ("type_line", models.CharField(blank=True, default="", max_length=255)),
                ("legalities", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
