# Generated by Django 4.2.30 on 2026-08-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0116_oracle_card"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="imageevidence",
            index=models.Index(
                condition=models.Q(("artbox_phash__isnull", False)),
                fields=["artbox_phash"],
                name="imgevid_artbox_phash_idx",
            ),
        ),
    ]
