# Generated by Django 4.2.30 on 2026-08-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0116_oracle_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_second_call_bottom",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_second_call_left",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_second_call_right",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_second_call_top",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_second_frac_bottom",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_second_frac_left",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_second_frac_right",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="pinline_inset_second_frac_top",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
