# Generated by Django 4.2.30 on 2026-08-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0117_imageevidence_artbox_phash_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="parsed_collector_number",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="card",
            name="raw_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
