# Generated by Django 4.2.30 on 2026-08-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0118_card_parsed_collector_number_card_raw_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardscanlog",
            name="frame_mismatch_direction",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
