# Generated by Django 4.2.30 on 2026-09-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0120_card_content_phash_bands"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageevidence",
            name="frame_family_class",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="frame_family_confidence",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageevidence",
            name="frame_family_method",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
