# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0121_imageevidence_frame_family_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageevidence",
            name="frame_family_candidate_families",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
