# mypy: ignore-errors
# ruff: noqa
"""
Generated by quicktype. Do not manually modify this file.
"""

from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Type, TypeVar, Union, cast

from pydantic import BaseModel

T = TypeVar("T")
EnumT = TypeVar("EnumT", bound=Enum)


def from_str(x: Any) -> str:
    assert isinstance(x, str)
    return x


def from_bool(x: Any) -> bool:
    assert isinstance(x, bool)
    return x


def from_none(x: Any) -> Any:
    assert x is None
    return x


def from_union(fs, x):
    for f in fs:
        try:
            return f(x)
        except:
            pass
    assert False


def from_int(x: Any) -> int:
    assert isinstance(x, int) and not isinstance(x, bool)
    return x


def from_list(f: Callable[[Any], T], x: Any) -> List[T]:
    assert isinstance(x, list)
    return [f(y) for y in x]


def to_enum(c: Type[EnumT], x: Any) -> EnumT:
    assert isinstance(x, c)
    return x.value


def to_class(c: Type[T], x: Any) -> dict:
    assert isinstance(x, c)
    return cast(Any, x).to_dict()


def from_dict(f: Callable[[Any], T], x: Any) -> Dict[str, T]:
    assert isinstance(x, dict)
    return {k: f(v) for (k, v) in x.items()}


def from_float(x: Any) -> float:
    assert isinstance(x, (float, int)) and not isinstance(x, bool)
    return float(x)


def to_float(x: Any) -> float:
    assert isinstance(x, (int, float))
    return x


class Game(str, Enum):
    MTG = "MTG"


class PrintingCandidate(BaseModel):
    artist: str
    borderColor: str
    canonicalId: str
    collectorNumber: str
    expansionCode: str
    expansionName: str
    frame: str
    fullArt: bool
    identifier: str
    isBorderless: bool
    isEtched: bool
    isExtendedArt: bool
    isShowcase: bool
    mediumThumbnailUrl: str
    smallThumbnailUrl: str
    releasedAt: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "PrintingCandidate":
        assert isinstance(obj, dict)
        artist = from_str(obj.get("artist"))
        borderColor = from_str(obj.get("borderColor"))
        canonicalId = from_str(obj.get("canonicalId"))
        collectorNumber = from_str(obj.get("collectorNumber"))
        expansionCode = from_str(obj.get("expansionCode"))
        expansionName = from_str(obj.get("expansionName"))
        frame = from_str(obj.get("frame"))
        fullArt = from_bool(obj.get("fullArt"))
        identifier = from_str(obj.get("identifier"))
        isBorderless = from_bool(obj.get("isBorderless"))
        isEtched = from_bool(obj.get("isEtched"))
        isExtendedArt = from_bool(obj.get("isExtendedArt"))
        isShowcase = from_bool(obj.get("isShowcase"))
        mediumThumbnailUrl = from_str(obj.get("mediumThumbnailUrl"))
        smallThumbnailUrl = from_str(obj.get("smallThumbnailUrl"))
        releasedAt = from_union([from_none, from_str], obj.get("releasedAt"))
        return PrintingCandidate(
            artist,
            borderColor,
            canonicalId,
            collectorNumber,
            expansionCode,
            expansionName,
            frame,
            fullArt,
            identifier,
            isBorderless,
            isEtched,
            isExtendedArt,
            isShowcase,
            mediumThumbnailUrl,
            smallThumbnailUrl,
            releasedAt,
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["artist"] = from_str(self.artist)
        result["borderColor"] = from_str(self.borderColor)
        result["canonicalId"] = from_str(self.canonicalId)
        result["collectorNumber"] = from_str(self.collectorNumber)
        result["expansionCode"] = from_str(self.expansionCode)
        result["expansionName"] = from_str(self.expansionName)
        result["frame"] = from_str(self.frame)
        result["fullArt"] = from_bool(self.fullArt)
        result["identifier"] = from_str(self.identifier)
        result["isBorderless"] = from_bool(self.isBorderless)
        result["isEtched"] = from_bool(self.isEtched)
        result["isExtendedArt"] = from_bool(self.isExtendedArt)
        result["isShowcase"] = from_bool(self.isShowcase)
        result["mediumThumbnailUrl"] = from_str(self.mediumThumbnailUrl)
        result["smallThumbnailUrl"] = from_str(self.smallThumbnailUrl)
        if self.releasedAt is not None:
            result["releasedAt"] = from_union([from_none, from_str], self.releasedAt)
        return result


class CanonicalArtistClass(BaseModel):
    name: str

    @staticmethod
    def from_dict(obj: Any) -> "CanonicalArtistClass":
        assert isinstance(obj, dict)
        name = from_str(obj.get("name"))
        return CanonicalArtistClass(name)

    def to_dict(self) -> dict:
        result: dict = {}
        result["name"] = from_str(self.name)
        return result


class CanonicalCardClass(BaseModel):
    collectorNumber: str
    expansionCode: str
    expansionName: str
    identifier: str
    mediumThumbnailUrl: str
    smallThumbnailUrl: str
    artist: Optional[str] = None
    canonicalId: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "CanonicalCardClass":
        assert isinstance(obj, dict)
        collectorNumber = from_str(obj.get("collectorNumber"))
        expansionCode = from_str(obj.get("expansionCode"))
        expansionName = from_str(obj.get("expansionName"))
        identifier = from_str(obj.get("identifier"))
        mediumThumbnailUrl = from_str(obj.get("mediumThumbnailUrl"))
        smallThumbnailUrl = from_str(obj.get("smallThumbnailUrl"))
        artist = from_union([from_str, from_none], obj.get("artist"))
        canonicalId = from_union([from_str, from_none], obj.get("canonicalId"))
        return CanonicalCardClass(
            collectorNumber,
            expansionCode,
            expansionName,
            identifier,
            mediumThumbnailUrl,
            smallThumbnailUrl,
            artist,
            canonicalId,
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["collectorNumber"] = from_str(self.collectorNumber)
        result["expansionCode"] = from_str(self.expansionCode)
        result["expansionName"] = from_str(self.expansionName)
        result["identifier"] = from_str(self.identifier)
        result["mediumThumbnailUrl"] = from_str(self.mediumThumbnailUrl)
        result["smallThumbnailUrl"] = from_str(self.smallThumbnailUrl)
        if self.artist is not None:
            result["artist"] = from_union([from_str, from_none], self.artist)
        if self.canonicalId is not None:
            result["canonicalId"] = from_union([from_str, from_none], self.canonicalId)
        return result


class CardType(str, Enum):
    CARD = "CARD"
    CARDBACK = "CARDBACK"
    TOKEN = "TOKEN"


class PrintingTagStatus(str, Enum):
    """Community printing-tag vote consensus status for this card. Only RESOLVED cards have a
    community-confirmed printing behind canonicalCard (via inferred_canonical_card) - used by
    the frontend to show a 'matched by community tags' indicator and is otherwise
    informational.
    """

    nomatch = "no_match"
    resolved = "resolved"
    unresolved = "unresolved"


class SourceType(str, Enum):
    AWSS3 = "AWS S3"
    GoogleDrive = "Google Drive"
    LocalFile = "Local File"


class Card(BaseModel):
    cardType: CardType
    dateCreated: str
    """Created date - formatted by backend"""

    dateModified: str
    """Modified date - formatted by backend"""

    dpi: int
    extension: str
    identifier: str
    language: str
    mediumThumbnailUrl: str
    name: str
    printingTagStatus: PrintingTagStatus
    """Community printing-tag vote consensus status for this card. Only RESOLVED cards have a
    community-confirmed printing behind canonicalCard (via inferred_canonical_card) - used by
    the frontend to show a 'matched by community tags' indicator and is otherwise
    informational.
    """
    priority: int
    searchq: str
    size: int
    smallThumbnailUrl: str
    source: str
    sourceId: int
    sourceName: str
    sourceVerbose: str
    tags: List[str]
    canonicalArtist: Optional[CanonicalArtistClass] = None
    canonicalArtistIsFromVoteOnly: Optional[bool] = None
    """True only when canonicalArtist was supplied by artist-vote consensus alone, with no
    confirmed indexing match or resolved printing backing it - lets the frontend distinguish
    a confidently-known artist from a vote-derived one (e.g. for the ArtistVotePicker
    'wrong?' affordance) without needing to know serialise()'s fallback chain itself.
    """
    canonicalArtistSource: Optional[str] = None
    """Which rung of the artist fallback chain actually supplied canonicalArtist -
    debug/introspection field, not load-bearing for any current frontend logic.
    """
    canonicalCard: Optional[CanonicalCardClass] = None
    sourceExternalLink: Optional[str] = None
    sourceType: Optional[SourceType] = None

    @staticmethod
    def from_dict(obj: Any) -> "Card":
        assert isinstance(obj, dict)
        cardType = CardType(obj.get("cardType"))
        dateCreated = from_str(obj.get("dateCreated"))
        dateModified = from_str(obj.get("dateModified"))
        dpi = from_int(obj.get("dpi"))
        extension = from_str(obj.get("extension"))
        identifier = from_str(obj.get("identifier"))
        language = from_str(obj.get("language"))
        mediumThumbnailUrl = from_str(obj.get("mediumThumbnailUrl"))
        name = from_str(obj.get("name"))
        printingTagStatus = PrintingTagStatus(obj.get("printingTagStatus"))
        priority = from_int(obj.get("priority"))
        searchq = from_str(obj.get("searchq"))
        size = from_int(obj.get("size"))
        smallThumbnailUrl = from_str(obj.get("smallThumbnailUrl"))
        source = from_str(obj.get("source"))
        sourceId = from_int(obj.get("sourceId"))
        sourceName = from_str(obj.get("sourceName"))
        sourceVerbose = from_str(obj.get("sourceVerbose"))
        tags = from_list(from_str, obj.get("tags"))
        canonicalArtist = from_union([from_none, CanonicalArtistClass.from_dict], obj.get("canonicalArtist"))
        canonicalArtistIsFromVoteOnly = from_union([from_bool, from_none], obj.get("canonicalArtistIsFromVoteOnly"))
        canonicalArtistSource = from_union([from_none, from_str], obj.get("canonicalArtistSource"))
        canonicalCard = from_union([from_none, CanonicalCardClass.from_dict], obj.get("canonicalCard"))
        sourceExternalLink = from_union([from_str, from_none], obj.get("sourceExternalLink"))
        sourceType = from_union([SourceType, from_none], obj.get("sourceType"))
        return Card(
            cardType,
            dateCreated,
            dateModified,
            dpi,
            extension,
            identifier,
            language,
            mediumThumbnailUrl,
            name,
            printingTagStatus,
            priority,
            searchq,
            size,
            smallThumbnailUrl,
            source,
            sourceId,
            sourceName,
            sourceVerbose,
            tags,
            canonicalArtist,
            canonicalArtistIsFromVoteOnly,
            canonicalArtistSource,
            canonicalCard,
            sourceExternalLink,
            sourceType,
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["cardType"] = to_enum(CardType, self.cardType)
        result["dateCreated"] = from_str(self.dateCreated)
        result["dateModified"] = from_str(self.dateModified)
        result["dpi"] = from_int(self.dpi)
        result["extension"] = from_str(self.extension)
        result["identifier"] = from_str(self.identifier)
        result["language"] = from_str(self.language)
        result["mediumThumbnailUrl"] = from_str(self.mediumThumbnailUrl)
        result["name"] = from_str(self.name)
        result["printingTagStatus"] = to_enum(PrintingTagStatus, self.printingTagStatus)
        result["priority"] = from_int(self.priority)
        result["searchq"] = from_str(self.searchq)
        result["size"] = from_int(self.size)
        result["smallThumbnailUrl"] = from_str(self.smallThumbnailUrl)
        result["source"] = from_str(self.source)
        result["sourceId"] = from_int(self.sourceId)
        result["sourceName"] = from_str(self.sourceName)
        result["sourceVerbose"] = from_str(self.sourceVerbose)
        result["tags"] = from_list(from_str, self.tags)
        if self.canonicalArtist is not None:
            result["canonicalArtist"] = from_union(
                [from_none, lambda x: to_class(CanonicalArtistClass, x)], self.canonicalArtist
            )
        if self.canonicalArtistIsFromVoteOnly is not None:
            result["canonicalArtistIsFromVoteOnly"] = from_union(
                [from_bool, from_none], self.canonicalArtistIsFromVoteOnly
            )
        if self.canonicalArtistSource is not None:
            result["canonicalArtistSource"] = from_union([from_none, from_str], self.canonicalArtistSource)
        if self.canonicalCard is not None:
            result["canonicalCard"] = from_union(
                [from_none, lambda x: to_class(CanonicalCardClass, x)], self.canonicalCard
            )
        if self.sourceExternalLink is not None:
            result["sourceExternalLink"] = from_union([from_str, from_none], self.sourceExternalLink)
        if self.sourceType is not None:
            result["sourceType"] = from_union([lambda x: to_enum(SourceType, x), from_none], self.sourceType)
        return result


class TypeEnum(str, Enum):
    artist = "artist"
    confirmsuggestion = "confirm_suggestion"
    identifyprinting = "identify_printing"
    tag = "tag"


class QuestionFeedItem(BaseModel):
    card: Card
    type: TypeEnum
    candidates: Optional[List[PrintingCandidate]] = None
    confidentlyKnownArtistName: Optional[str] = None
    suggestedPrinting: Optional[PrintingCandidate] = None
    tagConfidence: Optional[Dict[str, float]] = None
    tagName: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "QuestionFeedItem":
        assert isinstance(obj, dict)
        card = Card.from_dict(obj.get("card"))
        type = TypeEnum(obj.get("type"))
        candidates = from_union([lambda x: from_list(PrintingCandidate.from_dict, x), from_none], obj.get("candidates"))
        confidentlyKnownArtistName = from_union([from_none, from_str], obj.get("confidentlyKnownArtistName"))
        suggestedPrinting = from_union([PrintingCandidate.from_dict, from_none], obj.get("suggestedPrinting"))
        tagConfidence = from_union([lambda x: from_dict(from_float, x), from_none], obj.get("tagConfidence"))
        tagName = from_union([from_str, from_none], obj.get("tagName"))
        return QuestionFeedItem(
            card, type, candidates, confidentlyKnownArtistName, suggestedPrinting, tagConfidence, tagName
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["card"] = to_class(Card, self.card)
        result["type"] = to_enum(TypeEnum, self.type)
        if self.candidates is not None:
            result["candidates"] = from_union(
                [lambda x: from_list(lambda x: to_class(PrintingCandidate, x), x), from_none], self.candidates
            )
        if self.confidentlyKnownArtistName is not None:
            result["confidentlyKnownArtistName"] = from_union([from_none, from_str], self.confidentlyKnownArtistName)
        if self.suggestedPrinting is not None:
            result["suggestedPrinting"] = from_union(
                [lambda x: to_class(PrintingCandidate, x), from_none], self.suggestedPrinting
            )
        if self.tagConfidence is not None:
            result["tagConfidence"] = from_union([lambda x: from_dict(to_float, x), from_none], self.tagConfidence)
        if self.tagName is not None:
            result["tagName"] = from_union([from_str, from_none], self.tagName)
        return result


class QuestionFeedCounts(BaseModel):
    confirmable: int
    contested: int
    fresh: int
    total: int

    @staticmethod
    def from_dict(obj: Any) -> "QuestionFeedCounts":
        assert isinstance(obj, dict)
        confirmable = from_int(obj.get("confirmable"))
        contested = from_int(obj.get("contested"))
        fresh = from_int(obj.get("fresh"))
        total = from_int(obj.get("total"))
        return QuestionFeedCounts(confirmable, contested, fresh, total)

    def to_dict(self) -> dict:
        result: dict = {}
        result["confirmable"] = from_int(self.confirmable)
        result["contested"] = from_int(self.contested)
        result["fresh"] = from_int(self.fresh)
        result["total"] = from_int(self.total)
        return result


class QuestionFeedResponse(BaseModel):
    remainingEstimate: QuestionFeedCounts
    item: Optional[QuestionFeedItem] = None

    @staticmethod
    def from_dict(obj: Any) -> "QuestionFeedResponse":
        assert isinstance(obj, dict)
        remainingEstimate = QuestionFeedCounts.from_dict(obj.get("remainingEstimate"))
        item = from_union([QuestionFeedItem.from_dict, from_none], obj.get("item"))
        return QuestionFeedResponse(remainingEstimate, item)

    def to_dict(self) -> dict:
        result: dict = {}
        result["remainingEstimate"] = to_class(QuestionFeedCounts, self.remainingEstimate)
        if self.item is not None:
            result["item"] = from_union([lambda x: to_class(QuestionFeedItem, x), from_none], self.item)
        return result


class ArtistCandidatesRequest(BaseModel):
    identifier: str
    query: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "ArtistCandidatesRequest":
        assert isinstance(obj, dict)
        identifier = from_str(obj.get("identifier"))
        query = from_union([from_none, from_str], obj.get("query"))
        return ArtistCandidatesRequest(identifier, query)

    def to_dict(self) -> dict:
        result: dict = {}
        result["identifier"] = from_str(self.identifier)
        if self.query is not None:
            result["query"] = from_union([from_none, from_str], self.query)
        return result


class ArtistCandidatesResponse(BaseModel):
    results: List[Optional[CanonicalArtistClass]]

    @staticmethod
    def from_dict(obj: Any) -> "ArtistCandidatesResponse":
        assert isinstance(obj, dict)
        results = from_list(lambda x: from_union([from_none, CanonicalArtistClass.from_dict], x), obj.get("results"))
        return ArtistCandidatesResponse(results)

    def to_dict(self) -> dict:
        result: dict = {}
        result["results"] = from_list(
            lambda x: from_union([from_none, lambda x: to_class(CanonicalArtistClass, x)], x), self.results
        )
        return result


class ArtistConsensusRequest(BaseModel):
    identifier: str

    @staticmethod
    def from_dict(obj: Any) -> "ArtistConsensusRequest":
        assert isinstance(obj, dict)
        identifier = from_str(obj.get("identifier"))
        return ArtistConsensusRequest(identifier)

    def to_dict(self) -> dict:
        result: dict = {}
        result["identifier"] = from_str(self.identifier)
        return result


class ArtistVoteTallyEntry(BaseModel):
    count: int
    isUnknown: bool
    artist: Optional[CanonicalArtistClass] = None

    @staticmethod
    def from_dict(obj: Any) -> "ArtistVoteTallyEntry":
        assert isinstance(obj, dict)
        count = from_int(obj.get("count"))
        isUnknown = from_bool(obj.get("isUnknown"))
        artist = from_union([from_none, CanonicalArtistClass.from_dict], obj.get("artist"))
        return ArtistVoteTallyEntry(count, isUnknown, artist)

    def to_dict(self) -> dict:
        result: dict = {}
        result["count"] = from_int(self.count)
        result["isUnknown"] = from_bool(self.isUnknown)
        if self.artist is not None:
            result["artist"] = from_union([from_none, lambda x: to_class(CanonicalArtistClass, x)], self.artist)
        return result


class ArtistConsensusResponse(BaseModel):
    isUnknown: bool
    voteTally: List[ArtistVoteTallyEntry]
    resolvedArtist: Optional[CanonicalArtistClass] = None

    @staticmethod
    def from_dict(obj: Any) -> "ArtistConsensusResponse":
        assert isinstance(obj, dict)
        isUnknown = from_bool(obj.get("isUnknown"))
        voteTally = from_list(ArtistVoteTallyEntry.from_dict, obj.get("voteTally"))
        resolvedArtist = from_union([from_none, CanonicalArtistClass.from_dict], obj.get("resolvedArtist"))
        return ArtistConsensusResponse(isUnknown, voteTally, resolvedArtist)

    def to_dict(self) -> dict:
        result: dict = {}
        result["isUnknown"] = from_bool(self.isUnknown)
        result["voteTally"] = from_list(lambda x: to_class(ArtistVoteTallyEntry, x), self.voteTally)
        if self.resolvedArtist is not None:
            result["resolvedArtist"] = from_union(
                [from_none, lambda x: to_class(CanonicalArtistClass, x)], self.resolvedArtist
            )
        return result


class FilterSettings(BaseModel):
    borderlessOnly: bool
    """Opt-in filter. When true, excludes cards whose community-resolved printing
    (printingTagStatus == RESOLVED) is confirmed not borderless. Cards without a resolved
    printing are never excluded by this filter - they're unknowns, not mismatches.
    """
    excludesTags: List[str]
    """The tags which the cards must *not* have to be included in search results"""

    fullArtOnly: bool
    """Opt-in filter. When true, excludes cards whose community-resolved printing
    (printingTagStatus == RESOLVED) is confirmed not full-art. Cards without a resolved
    printing are never excluded by this filter - they're unknowns, not mismatches.
    """
    includesTags: List[str]
    """The tags which the cards must have to be included in search results"""

    languages: List[str]
    """The language the cards have to be written in to be included in search results"""

    maximumDPI: int
    """The maximum DPI that cards can have to be included in search results"""

    maximumSize: int
    """The maximum filesize that cards can have to be included in search results"""

    minimumDPI: int
    """The minimum DPI that cards must meet to be included in search results"""

    @staticmethod
    def from_dict(obj: Any) -> "FilterSettings":
        assert isinstance(obj, dict)
        borderlessOnly = from_bool(obj.get("borderlessOnly"))
        excludesTags = from_list(from_str, obj.get("excludesTags"))
        fullArtOnly = from_bool(obj.get("fullArtOnly"))
        includesTags = from_list(from_str, obj.get("includesTags"))
        languages = from_list(from_str, obj.get("languages"))
        maximumDPI = from_int(obj.get("maximumDPI"))
        maximumSize = from_int(obj.get("maximumSize"))
        minimumDPI = from_int(obj.get("minimumDPI"))
        return FilterSettings(
            borderlessOnly, excludesTags, fullArtOnly, includesTags, languages, maximumDPI, maximumSize, minimumDPI
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["borderlessOnly"] = from_bool(self.borderlessOnly)
        result["excludesTags"] = from_list(from_str, self.excludesTags)
        result["fullArtOnly"] = from_bool(self.fullArtOnly)
        result["includesTags"] = from_list(from_str, self.includesTags)
        result["languages"] = from_list(from_str, self.languages)
        result["maximumDPI"] = from_int(self.maximumDPI)
        result["maximumSize"] = from_int(self.maximumSize)
        result["minimumDPI"] = from_int(self.minimumDPI)
        return result


class SearchTypeSettings(BaseModel):
    filterCardbacks: bool
    """Whether search settings apply to cardbacks or not"""

    fuzzySearch: bool
    """Whether fuzzy search is active"""

    @staticmethod
    def from_dict(obj: Any) -> "SearchTypeSettings":
        assert isinstance(obj, dict)
        filterCardbacks = from_bool(obj.get("filterCardbacks"))
        fuzzySearch = from_bool(obj.get("fuzzySearch"))
        return SearchTypeSettings(filterCardbacks, fuzzySearch)

    def to_dict(self) -> dict:
        result: dict = {}
        result["filterCardbacks"] = from_bool(self.filterCardbacks)
        result["fuzzySearch"] = from_bool(self.fuzzySearch)
        return result


class SourceSettings(BaseModel):
    sources: List[List[Union[int, bool]]]
    """The list of sources in the order they should be searched"""

    @staticmethod
    def from_dict(obj: Any) -> "SourceSettings":
        assert isinstance(obj, dict)
        sources = from_list(lambda x: from_list(lambda x: from_union([from_int, from_bool], x), x), obj.get("sources"))
        return SourceSettings(sources)

    def to_dict(self) -> dict:
        result: dict = {}
        result["sources"] = from_list(
            lambda x: from_list(lambda x: from_union([from_int, from_bool], x), x), self.sources
        )
        return result


class SearchSettings(BaseModel):
    filterSettings: FilterSettings
    searchTypeSettings: SearchTypeSettings
    sourceSettings: SourceSettings

    @staticmethod
    def from_dict(obj: Any) -> "SearchSettings":
        assert isinstance(obj, dict)
        filterSettings = FilterSettings.from_dict(obj.get("filterSettings"))
        searchTypeSettings = SearchTypeSettings.from_dict(obj.get("searchTypeSettings"))
        sourceSettings = SourceSettings.from_dict(obj.get("sourceSettings"))
        return SearchSettings(filterSettings, searchTypeSettings, sourceSettings)

    def to_dict(self) -> dict:
        result: dict = {}
        result["filterSettings"] = to_class(FilterSettings, self.filterSettings)
        result["searchTypeSettings"] = to_class(SearchTypeSettings, self.searchTypeSettings)
        result["sourceSettings"] = to_class(SourceSettings, self.sourceSettings)
        return result


class CardbacksRequest(BaseModel):
    searchSettings: SearchSettings

    @staticmethod
    def from_dict(obj: Any) -> "CardbacksRequest":
        assert isinstance(obj, dict)
        searchSettings = SearchSettings.from_dict(obj.get("searchSettings"))
        return CardbacksRequest(searchSettings)

    def to_dict(self) -> dict:
        result: dict = {}
        result["searchSettings"] = to_class(SearchSettings, self.searchSettings)
        return result


class CardbacksResponse(BaseModel):
    cardbacks: List[str]

    @staticmethod
    def from_dict(obj: Any) -> "CardbacksResponse":
        assert isinstance(obj, dict)
        cardbacks = from_list(from_str, obj.get("cardbacks"))
        return CardbacksResponse(cardbacks)

    def to_dict(self) -> dict:
        result: dict = {}
        result["cardbacks"] = from_list(from_str, self.cardbacks)
        return result


class CardsRequest(BaseModel):
    cardIdentifiers: List[str]

    @staticmethod
    def from_dict(obj: Any) -> "CardsRequest":
        assert isinstance(obj, dict)
        cardIdentifiers = from_list(from_str, obj.get("cardIdentifiers"))
        return CardsRequest(cardIdentifiers)

    def to_dict(self) -> dict:
        result: dict = {}
        result["cardIdentifiers"] = from_list(from_str, self.cardIdentifiers)
        return result


class CardsResponse(BaseModel):
    results: Dict[str, Card]

    @staticmethod
    def from_dict(obj: Any) -> "CardsResponse":
        assert isinstance(obj, dict)
        results = from_dict(Card.from_dict, obj.get("results"))
        return CardsResponse(results)

    def to_dict(self) -> dict:
        result: dict = {}
        result["results"] = from_dict(lambda x: to_class(Card, x), self.results)
        return result


class SourceContribution(BaseModel):
    avgdpi: str
    description: str
    name: str
    qtyCardbacks: str
    qtyCards: str
    qtyTokens: str
    size: str
    sourceType: SourceType
    externalLink: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "SourceContribution":
        assert isinstance(obj, dict)
        avgdpi = from_str(obj.get("avgdpi"))
        description = from_str(obj.get("description"))
        name = from_str(obj.get("name"))
        qtyCardbacks = from_str(obj.get("qtyCardbacks"))
        qtyCards = from_str(obj.get("qtyCards"))
        qtyTokens = from_str(obj.get("qtyTokens"))
        size = from_str(obj.get("size"))
        sourceType = SourceType(obj.get("sourceType"))
        externalLink = from_union([from_str, from_none], obj.get("externalLink"))
        return SourceContribution(
            avgdpi, description, name, qtyCardbacks, qtyCards, qtyTokens, size, sourceType, externalLink
        )

    def to_dict(self) -> dict:
        result: dict = {}
        result["avgdpi"] = from_str(self.avgdpi)
        result["description"] = from_str(self.description)
        result["name"] = from_str(self.name)
        result["qtyCardbacks"] = from_str(self.qtyCardbacks)
        result["qtyCards"] = from_str(self.qtyCards)
        result["qtyTokens"] = from_str(self.qtyTokens)
        result["size"] = from_str(self.size)
        result["sourceType"] = to_enum(SourceType, self.sourceType)
        if self.externalLink is not None:
            result["externalLink"] = from_union([from_str, from_none], self.externalLink)
        return result


class ContributionsResponse(BaseModel):
    cardCountByType: Dict[str, int]
    sources: List[SourceContribution]
    totalDatabaseSize: int

    @staticmethod
    def from_dict(obj: Any) -> "ContributionsResponse":
        assert isinstance(obj, dict)
        cardCountByType = from_dict(from_int, obj.get("cardCountByType"))
        sources = from_list(SourceContribution.from_dict, obj.get("sources"))
        totalDatabaseSize = from_int(obj.get("totalDatabaseSize"))
        return ContributionsResponse(cardCountByType, sources, totalDatabaseSize)

    def to_dict(self) -> dict:
        result: dict = {}
        result["cardCountByType"] = from_dict(from_int, self.cardCountByType)
        result["sources"] = from_list(lambda x: to_class(SourceContribution, x), self.sources)
        result["totalDatabaseSize"] = from_int(self.totalDatabaseSize)
        return result


class DFCPairsResponse(BaseModel):
    dfcPairs: Dict[str, str]

    @staticmethod
    def from_dict(obj: Any) -> "DFCPairsResponse":
        assert isinstance(obj, dict)
        dfcPairs = from_dict(from_str, obj.get("dfcPairs"))
        return DFCPairsResponse(dfcPairs)

    def to_dict(self) -> dict:
        result: dict = {}
        result["dfcPairs"] = from_dict(from_str, self.dfcPairs)
        return result


class SearchQuery(BaseModel):
    cardType: CardType
    collectorNumber: Optional[str] = None
    expansionCode: Optional[str] = None
    query: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "SearchQuery":
        assert isinstance(obj, dict)
        cardType = CardType(obj.get("cardType"))
        collectorNumber = from_union([from_str, from_none], obj.get("collectorNumber"))
        expansionCode = from_union([from_str, from_none], obj.get("expansionCode"))
        query = from_union([from_none, from_str], obj.get("query"))
        return SearchQuery(cardType, collectorNumber, expansionCode, query)

    def to_dict(self) -> dict:
        result: dict = {}
        result["cardType"] = to_enum(CardType, self.cardType)
        if self.collectorNumber is not None:
            result["collectorNumber"] = from_union([from_str, from_none], self.collectorNumber)
        if self.expansionCode is not None:
            result["expansionCode"] = from_union([from_str, from_none], self.expansionCode)
        result["query"] = from_union([from_none, from_str], self.query)
        return result


class EditorSearchRequest(BaseModel):
    queries: Dict[str, SearchQuery]
    searchSettings: SearchSettings

    @staticmethod
    def from_dict(obj: Any) -> "EditorSearchRequest":
        assert isinstance(obj, dict)
        queries = from_dict(SearchQuery.from_dict, obj.get("queries"))
        searchSettings = SearchSettings.from_dict(obj.get("searchSettings"))
        return EditorSearchRequest(queries, searchSettings)

    def to_dict(self) -> dict:
        result: dict = {}
        result["queries"] = from_dict(lambda x: to_class(SearchQuery, x), self.queries)
        result["searchSettings"] = to_class(SearchSettings, self.searchSettings)
        return result


class EditorSearchResponse(BaseModel):
    degradedQueries: List[str]
    """Hash keys (matching `results`' own keys) of queries whose printing-specific search
    (expansion_code and/or collector_number) found zero hits under that filter and were
    retried without it. Absence from this list means either the query carried no printing
    filter at all, or the filter found real hits - exact-match behaviour when hits exist is
    completely unaffected by this field.
    """
    results: Dict[str, List[str]]

    @staticmethod
    def from_dict(obj: Any) -> "EditorSearchResponse":
        assert isinstance(obj, dict)
        degradedQueries = from_list(from_str, obj.get("degradedQueries"))
        results = from_dict(lambda x: from_list(from_str, x), obj.get("results"))
        return EditorSearchResponse(degradedQueries, results)

    def to_dict(self) -> dict:
        result: dict = {}
        result["degradedQueries"] = from_list(from_str, self.degradedQueries)
        result["results"] = from_dict(lambda x: from_list(from_str, x), self.results)
        return result


class ErrorResponse(BaseModel):
    name: str
    errors: Optional[List[Dict[str, Any]]] = None
    message: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "ErrorResponse":
        assert isinstance(obj, dict)
        name = from_str(obj.get("name"))
        errors = from_union([lambda x: from_list(lambda x: from_dict(lambda x: x, x), x), from_none], obj.get("errors"))
        message = from_union([from_str, from_none], obj.get("message"))
        return ErrorResponse(name, errors, message)

    def to_dict(self) -> dict:
        result: dict = {}
        result["name"] = from_str(self.name)
        if self.errors is not None:
            result["errors"] = from_union(
                [lambda x: from_list(lambda x: from_dict(lambda x: x, x), x), from_none], self.errors
            )
        if self.message is not None:
            result["message"] = from_union([from_str, from_none], self.message)
        return result


class SortBy(str, Enum):
    dateCreatedAscending = "dateCreatedAscending"
    dateCreatedDescending = "dateCreatedDescending"
    dateModifiedAscending = "dateModifiedAscending"
    dateModifiedDescending = "dateModifiedDescending"
    nameAscending = "nameAscending"
    nameDescending = "nameDescending"


class ExploreSearchRequest(BaseModel):
    cardTypes: List[CardType]
    pageSize: int
    pageStart: int
    searchSettings: SearchSettings
    sortBy: SortBy
    query: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "ExploreSearchRequest":
        assert isinstance(obj, dict)
        cardTypes = from_list(CardType, obj.get("cardTypes"))
        pageSize = from_int(obj.get("pageSize"))
        pageStart = from_int(obj.get("pageStart"))
        searchSettings = SearchSettings.from_dict(obj.get("searchSettings"))
        sortBy = SortBy(obj.get("sortBy"))
        query = from_union([from_none, from_str], obj.get("query"))
        return ExploreSearchRequest(cardTypes, pageSize, pageStart, searchSettings, sortBy, query)

    def to_dict(self) -> dict:
        result: dict = {}
        result["cardTypes"] = from_list(lambda x: to_enum(CardType, x), self.cardTypes)
        result["pageSize"] = from_int(self.pageSize)
        result["pageStart"] = from_int(self.pageStart)
        result["searchSettings"] = to_class(SearchSettings, self.searchSettings)
        result["sortBy"] = to_enum(SortBy, self.sortBy)
        result["query"] = from_union([from_none, from_str], self.query)
        return result


class ExploreSearchResponse(BaseModel):
    cards: List[Card]
    count: int

    @staticmethod
    def from_dict(obj: Any) -> "ExploreSearchResponse":
        assert isinstance(obj, dict)
        cards = from_list(Card.from_dict, obj.get("cards"))
        count = from_int(obj.get("count"))
        return ExploreSearchResponse(cards, count)

    def to_dict(self) -> dict:
        result: dict = {}
        result["cards"] = from_list(lambda x: to_class(Card, x), self.cards)
        result["count"] = from_int(self.count)
        return result


class ImportSiteDecklistRequest(BaseModel):
    url: str

    @staticmethod
    def from_dict(obj: Any) -> "ImportSiteDecklistRequest":
        assert isinstance(obj, dict)
        url = from_str(obj.get("url"))
        return ImportSiteDecklistRequest(url)

    def to_dict(self) -> dict:
        result: dict = {}
        result["url"] = from_str(self.url)
        return result


class ImportSiteDecklistResponse(BaseModel):
    cards: str

    @staticmethod
    def from_dict(obj: Any) -> "ImportSiteDecklistResponse":
        assert isinstance(obj, dict)
        cards = from_str(obj.get("cards"))
        return ImportSiteDecklistResponse(cards)

    def to_dict(self) -> dict:
        result: dict = {}
        result["cards"] = from_str(self.cards)
        return result


class ImportSite(BaseModel):
    name: str
    url: str

    @staticmethod
    def from_dict(obj: Any) -> "ImportSite":
        assert isinstance(obj, dict)
        name = from_str(obj.get("name"))
        url = from_str(obj.get("url"))
        return ImportSite(name, url)

    def to_dict(self) -> dict:
        result: dict = {}
        result["name"] = from_str(self.name)
        result["url"] = from_str(self.url)
        return result


class ImportSitesResponse(BaseModel):
    importSites: List[ImportSite]

    @staticmethod
    def from_dict(obj: Any) -> "ImportSitesResponse":
        assert isinstance(obj, dict)
        importSites = from_list(ImportSite.from_dict, obj.get("importSites"))
        return ImportSitesResponse(importSites)

    def to_dict(self) -> dict:
        result: dict = {}
        result["importSites"] = from_list(lambda x: to_class(ImportSite, x), self.importSites)
        return result


class Info(BaseModel):
    description: Optional[str] = None
    discord: Optional[str] = None
    email: Optional[str] = None
    name: Optional[str] = None
    reddit: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "Info":
        assert isinstance(obj, dict)
        description = from_union([from_none, from_str], obj.get("description"))
        discord = from_union([from_none, from_str], obj.get("discord"))
        email = from_union([from_none, from_str], obj.get("email"))
        name = from_union([from_none, from_str], obj.get("name"))
        reddit = from_union([from_none, from_str], obj.get("reddit"))
        return Info(description, discord, email, name, reddit)

    def to_dict(self) -> dict:
        result: dict = {}
        result["description"] = from_union([from_none, from_str], self.description)
        result["discord"] = from_union([from_none, from_str], self.discord)
        result["email"] = from_union([from_none, from_str], self.email)
        result["name"] = from_union([from_none, from_str], self.name)
        result["reddit"] = from_union([from_none, from_str], self.reddit)
        return result


class InfoResponse(BaseModel):
    info: Info

    @staticmethod
    def from_dict(obj: Any) -> "InfoResponse":
        assert isinstance(obj, dict)
        info = Info.from_dict(obj.get("info"))
        return InfoResponse(info)

    def to_dict(self) -> dict:
        result: dict = {}
        result["info"] = to_class(Info, self.info)
        return result


class Language(BaseModel):
    code: str
    name: str

    @staticmethod
    def from_dict(obj: Any) -> "Language":
        assert isinstance(obj, dict)
        code = from_str(obj.get("code"))
        name = from_str(obj.get("name"))
        return Language(code, name)

    def to_dict(self) -> dict:
        result: dict = {}
        result["code"] = from_str(self.code)
        result["name"] = from_str(self.name)
        return result


class LanguagesResponse(BaseModel):
    languages: List[Language]

    @staticmethod
    def from_dict(obj: Any) -> "LanguagesResponse":
        assert isinstance(obj, dict)
        languages = from_list(Language.from_dict, obj.get("languages"))
        return LanguagesResponse(languages)

    def to_dict(self) -> dict:
        result: dict = {}
        result["languages"] = from_list(lambda x: to_class(Language, x), self.languages)
        return result


class ModerationDriveCardsRequest(BaseModel):
    page: int
    sourceId: int

    @staticmethod
    def from_dict(obj: Any) -> "ModerationDriveCardsRequest":
        assert isinstance(obj, dict)
        page = from_int(obj.get("page"))
        sourceId = from_int(obj.get("sourceId"))
        return ModerationDriveCardsRequest(page, sourceId)

    def to_dict(self) -> dict:
        result: dict = {}
        result["page"] = from_int(self.page)
        result["sourceId"] = from_int(self.sourceId)
        return result


class Source(BaseModel):
    description: str
    key: str
    name: str
    pk: int
    """Primary key"""

    sourceType: SourceType
    externalLink: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "Source":
        assert isinstance(obj, dict)
        description = from_str(obj.get("description"))
        key = from_str(obj.get("key"))
        name = from_str(obj.get("name"))
        pk = from_int(obj.get("pk"))
        sourceType = SourceType(obj.get("sourceType"))
        externalLink = from_union([from_str, from_none], obj.get("externalLink"))
        return Source(description, key, name, pk, sourceType, externalLink)

    def to_dict(self) -> dict:
        result: dict = {}
        result["description"] = from_str(self.description)
        result["key"] = from_str(self.key)
        result["name"] = from_str(self.name)
        result["pk"] = from_int(self.pk)
        result["sourceType"] = to_enum(SourceType, self.sourceType)
        if self.externalLink is not None:
            result["externalLink"] = from_union([from_str, from_none], self.externalLink)
        return result


class ModerationDriveCardsResponse(BaseModel):
    cards: List[Card]
    hits: int
    pages: int
    source: Source

    @staticmethod
    def from_dict(obj: Any) -> "ModerationDriveCardsResponse":
        assert isinstance(obj, dict)
        cards = from_list(Card.from_dict, obj.get("cards"))
        hits = from_int(obj.get("hits"))
        pages = from_int(obj.get("pages"))
        source = Source.from_dict(obj.get("source"))
        return ModerationDriveCardsResponse(cards, hits, pages, source)

    def to_dict(self) -> dict:
        result: dict = {}
        result["cards"] = from_list(lambda x: to_class(Card, x), self.cards)
        result["hits"] = from_int(self.hits)
        result["pages"] = from_int(self.pages)
        result["source"] = to_class(Source, self.source)
        return result


class ModerationDrivesRequest(BaseModel):
    page: int

    @staticmethod
    def from_dict(obj: Any) -> "ModerationDrivesRequest":
        assert isinstance(obj, dict)
        page = from_int(obj.get("page"))
        return ModerationDrivesRequest(page)

    def to_dict(self) -> dict:
        result: dict = {}
        result["page"] = from_int(self.page)
        return result


class ModerationDriveItem(BaseModel):
    qtyCardbacks: int
    qtyCards: int
    qtyTokens: int
    source: Source

    @staticmethod
    def from_dict(obj: Any) -> "ModerationDriveItem":
        assert isinstance(obj, dict)
        qtyCardbacks = from_int(obj.get("qtyCardbacks"))
        qtyCards = from_int(obj.get("qtyCards"))
        qtyTokens = from_int(obj.get("qtyTokens"))
        source = Source.from_dict(obj.get("source"))
        return ModerationDriveItem(qtyCardbacks, qtyCards, qtyTokens, source)

    def to_dict(self) -> dict:
        result: dict = {}
        result["qtyCardbacks"] = from_int(self.qtyCardbacks)
        result["qtyCards"] = from_int(self.qtyCards)
        result["qtyTokens"] = from_int(self.qtyTokens)
        result["source"] = to_class(Source, self.source)
        return result


class ModerationDrivesResponse(BaseModel):
    hits: int
    items: List[ModerationDriveItem]
    pages: int

    @staticmethod
    def from_dict(obj: Any) -> "ModerationDrivesResponse":
        assert isinstance(obj, dict)
        hits = from_int(obj.get("hits"))
        items = from_list(ModerationDriveItem.from_dict, obj.get("items"))
        pages = from_int(obj.get("pages"))
        return ModerationDrivesResponse(hits, items, pages)

    def to_dict(self) -> dict:
        result: dict = {}
        result["hits"] = from_int(self.hits)
        result["items"] = from_list(lambda x: to_class(ModerationDriveItem, x), self.items)
        result["pages"] = from_int(self.pages)
        return result


class ModerationQueueRequest(BaseModel):
    page: int

    @staticmethod
    def from_dict(obj: Any) -> "ModerationQueueRequest":
        assert isinstance(obj, dict)
        page = from_int(obj.get("page"))
        return ModerationQueueRequest(page)

    def to_dict(self) -> dict:
        result: dict = {}
        result["page"] = from_int(self.page)
        return result


class ModerationQueueItem(BaseModel):
    card: Card
    reportCount: int
    reportExcerpts: List[str]
    tagName: str

    @staticmethod
    def from_dict(obj: Any) -> "ModerationQueueItem":
        assert isinstance(obj, dict)
        card = Card.from_dict(obj.get("card"))
        reportCount = from_int(obj.get("reportCount"))
        reportExcerpts = from_list(from_str, obj.get("reportExcerpts"))
        tagName = from_str(obj.get("tagName"))
        return ModerationQueueItem(card, reportCount, reportExcerpts, tagName)

    def to_dict(self) -> dict:
        result: dict = {}
        result["card"] = to_class(Card, self.card)
        result["reportCount"] = from_int(self.reportCount)
        result["reportExcerpts"] = from_list(from_str, self.reportExcerpts)
        result["tagName"] = from_str(self.tagName)
        return result


class ModerationQueueResponse(BaseModel):
    hits: int
    items: List[ModerationQueueItem]
    pages: int

    @staticmethod
    def from_dict(obj: Any) -> "ModerationQueueResponse":
        assert isinstance(obj, dict)
        hits = from_int(obj.get("hits"))
        items = from_list(ModerationQueueItem.from_dict, obj.get("items"))
        pages = from_int(obj.get("pages"))
        return ModerationQueueResponse(hits, items, pages)

    def to_dict(self) -> dict:
        result: dict = {}
        result["hits"] = from_int(self.hits)
        result["items"] = from_list(lambda x: to_class(ModerationQueueItem, x), self.items)
        result["pages"] = from_int(self.pages)
        return result


class ModerationRemoveCardRequest(BaseModel):
    identifier: str

    @staticmethod
    def from_dict(obj: Any) -> "ModerationRemoveCardRequest":
        assert isinstance(obj, dict)
        identifier = from_str(obj.get("identifier"))
        return ModerationRemoveCardRequest(identifier)

    def to_dict(self) -> dict:
        result: dict = {}
        result["identifier"] = from_str(self.identifier)
        return result


class ModerationRemoveCardResponse(BaseModel):
    removed: bool

    @staticmethod
    def from_dict(obj: Any) -> "ModerationRemoveCardResponse":
        assert isinstance(obj, dict)
        removed = from_bool(obj.get("removed"))
        return ModerationRemoveCardResponse(removed)

    def to_dict(self) -> dict:
        result: dict = {}
        result["removed"] = from_bool(self.removed)
        return result


class ModerationRemoveDriveRequest(BaseModel):
    sourceId: int

    @staticmethod
    def from_dict(obj: Any) -> "ModerationRemoveDriveRequest":
        assert isinstance(obj, dict)
        sourceId = from_int(obj.get("sourceId"))
        return ModerationRemoveDriveRequest(sourceId)

    def to_dict(self) -> dict:
        result: dict = {}
        result["sourceId"] = from_int(self.sourceId)
        return result


class ModerationRemoveDriveResponse(BaseModel):
    cardsRemoved: int
    removed: bool

    @staticmethod
    def from_dict(obj: Any) -> "ModerationRemoveDriveResponse":
        assert isinstance(obj, dict)
        cardsRemoved = from_int(obj.get("cardsRemoved"))
        removed = from_bool(obj.get("removed"))
        return ModerationRemoveDriveResponse(cardsRemoved, removed)

    def to_dict(self) -> dict:
        result: dict = {}
        result["cardsRemoved"] = from_int(self.cardsRemoved)
        result["removed"] = from_bool(self.removed)
        return result


class NewCardsFirstPage(BaseModel):
    cards: List[Card]
    hits: int
    pages: int
    source: Source

    @staticmethod
    def from_dict(obj: Any) -> "NewCardsFirstPage":
        assert isinstance(obj, dict)
        cards = from_list(Card.from_dict, obj.get("cards"))
        hits = from_int(obj.get("hits"))
        pages = from_int(obj.get("pages"))
        source = Source.from_dict(obj.get("source"))
        return NewCardsFirstPage(cards, hits, pages, source)

    def to_dict(self) -> dict:
        result: dict = {}
        result["cards"] = from_list(lambda x: to_class(Card, x), self.cards)
        result["hits"] = from_int(self.hits)
        result["pages"] = from_int(self.pages)
        result["source"] = to_class(Source, self.source)
        return result


class NewCardsFirstPagesResponse(BaseModel):
    results: Dict[str, NewCardsFirstPage]

    @staticmethod
    def from_dict(obj: Any) -> "NewCardsFirstPagesResponse":
        assert isinstance(obj, dict)
        results = from_dict(NewCardsFirstPage.from_dict, obj.get("results"))
        return NewCardsFirstPagesResponse(results)

    def to_dict(self) -> dict:
        result: dict = {}
        result["results"] = from_dict(lambda x: to_class(NewCardsFirstPage, x), self.results)
        return result


class NewCardsPageResponse(BaseModel):
    cards: List[Card]

    @staticmethod
    def from_dict(obj: Any) -> "NewCardsPageResponse":
        assert isinstance(obj, dict)
        cards = from_list(Card.from_dict, obj.get("cards"))
        return NewCardsPageResponse(cards)

    def to_dict(self) -> dict:
        result: dict = {}
        result["cards"] = from_list(lambda x: to_class(Card, x), self.cards)
        return result


class OldEditorSearchRequest(BaseModel):
    queries: List[SearchQuery]
    searchSettings: SearchSettings

    @staticmethod
    def from_dict(obj: Any) -> "OldEditorSearchRequest":
        assert isinstance(obj, dict)
        queries = from_list(SearchQuery.from_dict, obj.get("queries"))
        searchSettings = SearchSettings.from_dict(obj.get("searchSettings"))
        return OldEditorSearchRequest(queries, searchSettings)

    def to_dict(self) -> dict:
        result: dict = {}
        result["queries"] = from_list(lambda x: to_class(SearchQuery, x), self.queries)
        result["searchSettings"] = to_class(SearchSettings, self.searchSettings)
        return result


class OldEditorSearchResponse(BaseModel):
    results: Dict[str, Dict[str, List[str]]]

    @staticmethod
    def from_dict(obj: Any) -> "OldEditorSearchResponse":
        assert isinstance(obj, dict)
        results = from_dict(lambda x: from_dict(lambda x: from_list(from_str, x), x), obj.get("results"))
        return OldEditorSearchResponse(results)

    def to_dict(self) -> dict:
        result: dict = {}
        result["results"] = from_dict(lambda x: from_dict(lambda x: from_list(from_str, x), x), self.results)
        return result


class CampaignClass(BaseModel):
    about: str
    id: str

    @staticmethod
    def from_dict(obj: Any) -> "CampaignClass":
        assert isinstance(obj, dict)
        about = from_str(obj.get("about"))
        id = from_str(obj.get("id"))
        return CampaignClass(about, id)

    def to_dict(self) -> dict:
        result: dict = {}
        result["about"] = from_str(self.about)
        result["id"] = from_str(self.id)
        return result


class Supporter(BaseModel):
    date: str
    name: str
    tier: str
    usd: float

    @staticmethod
    def from_dict(obj: Any) -> "Supporter":
        assert isinstance(obj, dict)
        date = from_str(obj.get("date"))
        name = from_str(obj.get("name"))
        tier = from_str(obj.get("tier"))
        usd = from_float(obj.get("usd"))
        return Supporter(date, name, tier, usd)

    def to_dict(self) -> dict:
        result: dict = {}
        result["date"] = from_str(self.date)
        result["name"] = from_str(self.name)
        result["tier"] = from_str(self.tier)
        result["usd"] = to_float(self.usd)
        return result


class SupporterTier(BaseModel):
    description: str
    title: str
    usd: float

    @staticmethod
    def from_dict(obj: Any) -> "SupporterTier":
        assert isinstance(obj, dict)
        description = from_str(obj.get("description"))
        title = from_str(obj.get("title"))
        usd = from_float(obj.get("usd"))
        return SupporterTier(description, title, usd)

    def to_dict(self) -> dict:
        result: dict = {}
        result["description"] = from_str(self.description)
        result["title"] = from_str(self.title)
        result["usd"] = to_float(self.usd)
        return result


class Patreon(BaseModel):
    members: List[Supporter]
    campaign: Optional[CampaignClass] = None
    tiers: Optional[Dict[str, SupporterTier]] = None
    url: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "Patreon":
        assert isinstance(obj, dict)
        members = from_list(Supporter.from_dict, obj.get("members"))
        campaign = from_union([from_none, CampaignClass.from_dict], obj.get("campaign"))
        tiers = from_union([from_none, lambda x: from_dict(SupporterTier.from_dict, x)], obj.get("tiers"))
        url = from_union([from_none, from_str], obj.get("url"))
        return Patreon(members, campaign, tiers, url)

    def to_dict(self) -> dict:
        result: dict = {}
        result["members"] = from_list(lambda x: to_class(Supporter, x), self.members)
        result["campaign"] = from_union([from_none, lambda x: to_class(CampaignClass, x)], self.campaign)
        result["tiers"] = from_union(
            [from_none, lambda x: from_dict(lambda x: to_class(SupporterTier, x), x)], self.tiers
        )
        result["url"] = from_union([from_none, from_str], self.url)
        return result


class PatreonResponse(BaseModel):
    patreon: Patreon

    @staticmethod
    def from_dict(obj: Any) -> "PatreonResponse":
        assert isinstance(obj, dict)
        patreon = Patreon.from_dict(obj.get("patreon"))
        return PatreonResponse(patreon)

    def to_dict(self) -> dict:
        result: dict = {}
        result["patreon"] = to_class(Patreon, self.patreon)
        return result


class PrintingCandidatesRequest(BaseModel):
    identifier: str
    query: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "PrintingCandidatesRequest":
        assert isinstance(obj, dict)
        identifier = from_str(obj.get("identifier"))
        query = from_union([from_none, from_str], obj.get("query"))
        return PrintingCandidatesRequest(identifier, query)

    def to_dict(self) -> dict:
        result: dict = {}
        result["identifier"] = from_str(self.identifier)
        if self.query is not None:
            result["query"] = from_union([from_none, from_str], self.query)
        return result


class PrintingCandidatesResponse(BaseModel):
    results: List[PrintingCandidate]

    @staticmethod
    def from_dict(obj: Any) -> "PrintingCandidatesResponse":
        assert isinstance(obj, dict)
        results = from_list(PrintingCandidate.from_dict, obj.get("results"))
        return PrintingCandidatesResponse(results)

    def to_dict(self) -> dict:
        result: dict = {}
        result["results"] = from_list(lambda x: to_class(PrintingCandidate, x), self.results)
        return result


class PrintingConsensusRequest(BaseModel):
    identifier: str

    @staticmethod
    def from_dict(obj: Any) -> "PrintingConsensusRequest":
        assert isinstance(obj, dict)
        identifier = from_str(obj.get("identifier"))
        return PrintingConsensusRequest(identifier)

    def to_dict(self) -> dict:
        result: dict = {}
        result["identifier"] = from_str(self.identifier)
        return result


class VoteTallyEntry(BaseModel):
    count: int
    isNoMatch: bool
    printing: Optional[PrintingCandidate] = None

    @staticmethod
    def from_dict(obj: Any) -> "VoteTallyEntry":
        assert isinstance(obj, dict)
        count = from_int(obj.get("count"))
        isNoMatch = from_bool(obj.get("isNoMatch"))
        printing = from_union([PrintingCandidate.from_dict, from_none], obj.get("printing"))
        return VoteTallyEntry(count, isNoMatch, printing)

    def to_dict(self) -> dict:
        result: dict = {}
        result["count"] = from_int(self.count)
        result["isNoMatch"] = from_bool(self.isNoMatch)
        if self.printing is not None:
            result["printing"] = from_union([lambda x: to_class(PrintingCandidate, x), from_none], self.printing)
        return result


class PrintingConsensusResponse(BaseModel):
    isNoMatch: bool
    voteTally: List[VoteTallyEntry]
    resolvedPrinting: Optional[PrintingCandidate] = None

    @staticmethod
    def from_dict(obj: Any) -> "PrintingConsensusResponse":
        assert isinstance(obj, dict)
        isNoMatch = from_bool(obj.get("isNoMatch"))
        voteTally = from_list(VoteTallyEntry.from_dict, obj.get("voteTally"))
        resolvedPrinting = from_union([PrintingCandidate.from_dict, from_none], obj.get("resolvedPrinting"))
        return PrintingConsensusResponse(isNoMatch, voteTally, resolvedPrinting)

    def to_dict(self) -> dict:
        result: dict = {}
        result["isNoMatch"] = from_bool(self.isNoMatch)
        result["voteTally"] = from_list(lambda x: to_class(VoteTallyEntry, x), self.voteTally)
        if self.resolvedPrinting is not None:
            result["resolvedPrinting"] = from_union(
                [lambda x: to_class(PrintingCandidate, x), from_none], self.resolvedPrinting
            )
        return result


class PrintingTagQueueResponse(BaseModel):
    cards: List[Card]
    hits: int
    pages: int

    @staticmethod
    def from_dict(obj: Any) -> "PrintingTagQueueResponse":
        assert isinstance(obj, dict)
        cards = from_list(Card.from_dict, obj.get("cards"))
        hits = from_int(obj.get("hits"))
        pages = from_int(obj.get("pages"))
        return PrintingTagQueueResponse(cards, hits, pages)

    def to_dict(self) -> dict:
        result: dict = {}
        result["cards"] = from_list(lambda x: to_class(Card, x), self.cards)
        result["hits"] = from_int(self.hits)
        result["pages"] = from_int(self.pages)
        return result


class Reason(str, Enum):
    brokenimage = "broken_image"
    lowquality = "low_quality"
    nsfw = "nsfw"
    other = "other"
    wrongcard = "wrong_card"


class ReportCardRequest(BaseModel):
    anonymousId: str
    identifier: str
    reason: Reason
    text: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "ReportCardRequest":
        assert isinstance(obj, dict)
        anonymousId = from_str(obj.get("anonymousId"))
        identifier = from_str(obj.get("identifier"))
        reason = Reason(obj.get("reason"))
        text = from_union([from_str, from_none], obj.get("text"))
        return ReportCardRequest(anonymousId, identifier, reason, text)

    def to_dict(self) -> dict:
        result: dict = {}
        result["anonymousId"] = from_str(self.anonymousId)
        result["identifier"] = from_str(self.identifier)
        result["reason"] = to_enum(Reason, self.reason)
        if self.text is not None:
            result["text"] = from_union([from_str, from_none], self.text)
        return result


class ReportCardResponse(BaseModel):
    reported: bool
    voteCast: bool

    @staticmethod
    def from_dict(obj: Any) -> "ReportCardResponse":
        assert isinstance(obj, dict)
        reported = from_bool(obj.get("reported"))
        voteCast = from_bool(obj.get("voteCast"))
        return ReportCardResponse(reported, voteCast)

    def to_dict(self) -> dict:
        result: dict = {}
        result["reported"] = from_bool(self.reported)
        result["voteCast"] = from_bool(self.voteCast)
        return result


class Cards(BaseModel):
    CARD: List[Card]
    CARDBACK: List[Card]
    TOKEN: List[Card]

    @staticmethod
    def from_dict(obj: Any) -> "Cards":
        assert isinstance(obj, dict)
        CARD = from_list(Card.from_dict, obj.get("CARD"))
        CARDBACK = from_list(Card.from_dict, obj.get("CARDBACK"))
        TOKEN = from_list(Card.from_dict, obj.get("TOKEN"))
        return Cards(CARD, CARDBACK, TOKEN)

    def to_dict(self) -> dict:
        result: dict = {}
        result["CARD"] = from_list(lambda x: to_class(Card, x), self.CARD)
        result["CARDBACK"] = from_list(lambda x: to_class(Card, x), self.CARDBACK)
        result["TOKEN"] = from_list(lambda x: to_class(Card, x), self.TOKEN)
        return result


class SampleCardsResponse(BaseModel):
    cards: Cards

    @staticmethod
    def from_dict(obj: Any) -> "SampleCardsResponse":
        assert isinstance(obj, dict)
        cards = Cards.from_dict(obj.get("cards"))
        return SampleCardsResponse(cards)

    def to_dict(self) -> dict:
        result: dict = {}
        result["cards"] = to_class(Cards, self.cards)
        return result


class SearchEngineHealthResponse(BaseModel):
    online: bool

    @staticmethod
    def from_dict(obj: Any) -> "SearchEngineHealthResponse":
        assert isinstance(obj, dict)
        online = from_bool(obj.get("online"))
        return SearchEngineHealthResponse(online)

    def to_dict(self) -> dict:
        result: dict = {}
        result["online"] = from_bool(self.online)
        return result


class SourcesResponse(BaseModel):
    results: Dict[str, Source]

    @staticmethod
    def from_dict(obj: Any) -> "SourcesResponse":
        assert isinstance(obj, dict)
        results = from_dict(Source.from_dict, obj.get("results"))
        return SourcesResponse(results)

    def to_dict(self) -> dict:
        result: dict = {}
        result["results"] = from_dict(lambda x: to_class(Source, x), self.results)
        return result


class SubmitArtistVoteRequest(BaseModel):
    anonymousId: str
    identifier: str
    isUnknown: bool
    artistName: Optional[str] = None
    voteSurface: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "SubmitArtistVoteRequest":
        assert isinstance(obj, dict)
        anonymousId = from_str(obj.get("anonymousId"))
        identifier = from_str(obj.get("identifier"))
        isUnknown = from_bool(obj.get("isUnknown"))
        artistName = from_union([from_none, from_str], obj.get("artistName"))
        voteSurface = from_union([from_none, from_str], obj.get("voteSurface"))
        return SubmitArtistVoteRequest(anonymousId, identifier, isUnknown, artistName, voteSurface)

    def to_dict(self) -> dict:
        result: dict = {}
        result["anonymousId"] = from_str(self.anonymousId)
        result["identifier"] = from_str(self.identifier)
        result["isUnknown"] = from_bool(self.isUnknown)
        if self.artistName is not None:
            result["artistName"] = from_union([from_none, from_str], self.artistName)
        if self.voteSurface is not None:
            result["voteSurface"] = from_union([from_none, from_str], self.voteSurface)
        return result


class SubmitPrintingTagRequest(BaseModel):
    anonymousId: str
    identifier: str
    isNoMatch: bool
    printingIdentifier: Optional[str] = None
    voteSurface: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "SubmitPrintingTagRequest":
        assert isinstance(obj, dict)
        anonymousId = from_str(obj.get("anonymousId"))
        identifier = from_str(obj.get("identifier"))
        isNoMatch = from_bool(obj.get("isNoMatch"))
        printingIdentifier = from_union([from_none, from_str], obj.get("printingIdentifier"))
        voteSurface = from_union([from_none, from_str], obj.get("voteSurface"))
        return SubmitPrintingTagRequest(anonymousId, identifier, isNoMatch, printingIdentifier, voteSurface)

    def to_dict(self) -> dict:
        result: dict = {}
        result["anonymousId"] = from_str(self.anonymousId)
        result["identifier"] = from_str(self.identifier)
        result["isNoMatch"] = from_bool(self.isNoMatch)
        if self.printingIdentifier is not None:
            result["printingIdentifier"] = from_union([from_none, from_str], self.printingIdentifier)
        if self.voteSurface is not None:
            result["voteSurface"] = from_union([from_none, from_str], self.voteSurface)
        return result


class SubmitTagVoteRequest(BaseModel):
    anonymousId: str
    identifier: str
    polarity: int
    tagName: str
    voteSurface: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "SubmitTagVoteRequest":
        assert isinstance(obj, dict)
        anonymousId = from_str(obj.get("anonymousId"))
        identifier = from_str(obj.get("identifier"))
        polarity = from_int(obj.get("polarity"))
        tagName = from_str(obj.get("tagName"))
        voteSurface = from_union([from_none, from_str], obj.get("voteSurface"))
        return SubmitTagVoteRequest(anonymousId, identifier, polarity, tagName, voteSurface)

    def to_dict(self) -> dict:
        result: dict = {}
        result["anonymousId"] = from_str(self.anonymousId)
        result["identifier"] = from_str(self.identifier)
        result["polarity"] = from_int(self.polarity)
        result["tagName"] = from_str(self.tagName)
        if self.voteSurface is not None:
            result["voteSurface"] = from_union([from_none, from_str], self.voteSurface)
        return result


class TagConsensusRequest(BaseModel):
    identifier: str

    @staticmethod
    def from_dict(obj: Any) -> "TagConsensusRequest":
        assert isinstance(obj, dict)
        identifier = from_str(obj.get("identifier"))
        return TagConsensusRequest(identifier)

    def to_dict(self) -> dict:
        result: dict = {}
        result["identifier"] = from_str(self.identifier)
        return result


class TagVoteTallyEntry(BaseModel):
    count: int
    polarity: int

    @staticmethod
    def from_dict(obj: Any) -> "TagVoteTallyEntry":
        assert isinstance(obj, dict)
        count = from_int(obj.get("count"))
        polarity = from_int(obj.get("polarity"))
        return TagVoteTallyEntry(count, polarity)

    def to_dict(self) -> dict:
        result: dict = {}
        result["count"] = from_int(self.count)
        result["polarity"] = from_int(self.polarity)
        return result


class TagConsensusEntry(BaseModel):
    netPolarity: float
    tagName: str
    tally: List[TagVoteTallyEntry]
    resolvedPolarity: Optional[int] = None

    @staticmethod
    def from_dict(obj: Any) -> "TagConsensusEntry":
        assert isinstance(obj, dict)
        netPolarity = from_float(obj.get("netPolarity"))
        tagName = from_str(obj.get("tagName"))
        tally = from_list(TagVoteTallyEntry.from_dict, obj.get("tally"))
        resolvedPolarity = from_union([from_none, from_int], obj.get("resolvedPolarity"))
        return TagConsensusEntry(netPolarity, tagName, tally, resolvedPolarity)

    def to_dict(self) -> dict:
        result: dict = {}
        result["netPolarity"] = to_float(self.netPolarity)
        result["tagName"] = from_str(self.tagName)
        result["tally"] = from_list(lambda x: to_class(TagVoteTallyEntry, x), self.tally)
        if self.resolvedPolarity is not None:
            result["resolvedPolarity"] = from_union([from_none, from_int], self.resolvedPolarity)
        return result


class TagConsensusResponse(BaseModel):
    tags: List[TagConsensusEntry]

    @staticmethod
    def from_dict(obj: Any) -> "TagConsensusResponse":
        assert isinstance(obj, dict)
        tags = from_list(TagConsensusEntry.from_dict, obj.get("tags"))
        return TagConsensusResponse(tags)

    def to_dict(self) -> dict:
        result: dict = {}
        result["tags"] = from_list(lambda x: to_class(TagConsensusEntry, x), self.tags)
        return result


class ChildElement(BaseModel):
    children: List["ChildElement"]
    name: str
    aliases: Optional[List[str]] = None
    displayName: Optional[str] = None
    isEnabledByDefault: Optional[bool] = None
    parent: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "ChildElement":
        assert isinstance(obj, dict)
        children = from_list(ChildElement.from_dict, obj.get("children"))
        name = from_str(obj.get("name"))
        aliases = from_union([lambda x: from_list(from_str, x), from_none], obj.get("aliases"))
        displayName = from_union([from_none, from_str], obj.get("displayName"))
        isEnabledByDefault = from_union([from_bool, from_none], obj.get("isEnabledByDefault"))
        parent = from_union([from_none, from_str], obj.get("parent"))
        return ChildElement(children, name, aliases, displayName, isEnabledByDefault, parent)

    def to_dict(self) -> dict:
        result: dict = {}
        result["children"] = from_list(lambda x: to_class(ChildElement, x), self.children)
        result["name"] = from_str(self.name)
        if self.aliases is not None:
            result["aliases"] = from_union([lambda x: from_list(from_str, x), from_none], self.aliases)
        if self.displayName is not None:
            result["displayName"] = from_union([from_none, from_str], self.displayName)
        if self.isEnabledByDefault is not None:
            result["isEnabledByDefault"] = from_union([from_bool, from_none], self.isEnabledByDefault)
        result["parent"] = from_union([from_none, from_str], self.parent)
        return result


class Tag(BaseModel):
    children: List[ChildElement]
    name: str
    aliases: Optional[List[str]] = None
    displayName: Optional[str] = None
    isEnabledByDefault: Optional[bool] = None
    parent: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "Tag":
        assert isinstance(obj, dict)
        children = from_list(ChildElement.from_dict, obj.get("children"))
        name = from_str(obj.get("name"))
        aliases = from_union([lambda x: from_list(from_str, x), from_none], obj.get("aliases"))
        displayName = from_union([from_none, from_str], obj.get("displayName"))
        isEnabledByDefault = from_union([from_bool, from_none], obj.get("isEnabledByDefault"))
        parent = from_union([from_none, from_str], obj.get("parent"))
        return Tag(children, name, aliases, displayName, isEnabledByDefault, parent)

    def to_dict(self) -> dict:
        result: dict = {}
        result["children"] = from_list(lambda x: to_class(ChildElement, x), self.children)
        result["name"] = from_str(self.name)
        if self.aliases is not None:
            result["aliases"] = from_union([lambda x: from_list(from_str, x), from_none], self.aliases)
        if self.displayName is not None:
            result["displayName"] = from_union([from_none, from_str], self.displayName)
        if self.isEnabledByDefault is not None:
            result["isEnabledByDefault"] = from_union([from_bool, from_none], self.isEnabledByDefault)
        result["parent"] = from_union([from_none, from_str], self.parent)
        return result


class TagsResponse(BaseModel):
    tags: List[Tag]

    @staticmethod
    def from_dict(obj: Any) -> "TagsResponse":
        assert isinstance(obj, dict)
        tags = from_list(Tag.from_dict, obj.get("tags"))
        return TagsResponse(tags)

    def to_dict(self) -> dict:
        result: dict = {}
        result["tags"] = from_list(lambda x: to_class(Tag, x), self.tags)
        return result


class Kind(str, Enum):
    artist = "artist"
    printing = "printing"
    tag = "tag"


class VoteQueueRequest(BaseModel):
    kind: Kind
    page: int

    @staticmethod
    def from_dict(obj: Any) -> "VoteQueueRequest":
        assert isinstance(obj, dict)
        kind = Kind(obj.get("kind"))
        page = from_int(obj.get("page"))
        return VoteQueueRequest(kind, page)

    def to_dict(self) -> dict:
        result: dict = {}
        result["kind"] = to_enum(Kind, self.kind)
        result["page"] = from_int(self.page)
        return result


class VoteQueueItem(BaseModel):
    card: Card
    tagName: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "VoteQueueItem":
        assert isinstance(obj, dict)
        card = Card.from_dict(obj.get("card"))
        tagName = from_union([from_none, from_str], obj.get("tagName"))
        return VoteQueueItem(card, tagName)

    def to_dict(self) -> dict:
        result: dict = {}
        result["card"] = to_class(Card, self.card)
        if self.tagName is not None:
            result["tagName"] = from_union([from_none, from_str], self.tagName)
        return result


class VoteQueueResponse(BaseModel):
    hits: int
    items: List[VoteQueueItem]
    pages: int

    @staticmethod
    def from_dict(obj: Any) -> "VoteQueueResponse":
        assert isinstance(obj, dict)
        hits = from_int(obj.get("hits"))
        items = from_list(VoteQueueItem.from_dict, obj.get("items"))
        pages = from_int(obj.get("pages"))
        return VoteQueueResponse(hits, items, pages)

    def to_dict(self) -> dict:
        result: dict = {}
        result["hits"] = from_int(self.hits)
        result["items"] = from_list(lambda x: to_class(VoteQueueItem, x), self.items)
        result["pages"] = from_int(self.pages)
        return result


class WhoamiResponse(BaseModel):
    authenticated: bool
    discordEnabled: bool
    moderator: bool
    loginUrl: Optional[str] = None
    logoutUrl: Optional[str] = None
    username: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> "WhoamiResponse":
        assert isinstance(obj, dict)
        authenticated = from_bool(obj.get("authenticated"))
        discordEnabled = from_bool(obj.get("discordEnabled"))
        moderator = from_bool(obj.get("moderator"))
        loginUrl = from_union([from_none, from_str], obj.get("loginUrl"))
        logoutUrl = from_union([from_none, from_str], obj.get("logoutUrl"))
        username = from_union([from_none, from_str], obj.get("username"))
        return WhoamiResponse(authenticated, discordEnabled, moderator, loginUrl, logoutUrl, username)

    def to_dict(self) -> dict:
        result: dict = {}
        result["authenticated"] = from_bool(self.authenticated)
        result["discordEnabled"] = from_bool(self.discordEnabled)
        result["moderator"] = from_bool(self.moderator)
        result["loginUrl"] = from_union([from_none, from_str], self.loginUrl)
        result["logoutUrl"] = from_union([from_none, from_str], self.logoutUrl)
        result["username"] = from_union([from_none, from_str], self.username)
        return result


def ArtistVoteTallyEntryfromdict(s: Any) -> ArtistVoteTallyEntry:
    return ArtistVoteTallyEntry.from_dict(s)


def ArtistVoteTallyEntrytodict(x: ArtistVoteTallyEntry) -> Any:
    return to_class(ArtistVoteTallyEntry, x)


def Campaignfromdict(s: Any) -> Optional[CampaignClass]:
    return from_union([from_none, CampaignClass.from_dict], s)


def Campaigntodict(x: Optional[CampaignClass]) -> Any:
    return from_union([from_none, lambda x: to_class(CampaignClass, x)], x)


def CanonicalArtistfromdict(s: Any) -> Optional[CanonicalArtistClass]:
    return from_union([from_none, CanonicalArtistClass.from_dict], s)


def CanonicalArtisttodict(x: Optional[CanonicalArtistClass]) -> Any:
    return from_union([from_none, lambda x: to_class(CanonicalArtistClass, x)], x)


def CanonicalCardfromdict(s: Any) -> Optional[CanonicalCardClass]:
    return from_union([from_none, CanonicalCardClass.from_dict], s)


def CanonicalCardtodict(x: Optional[CanonicalCardClass]) -> Any:
    return from_union([from_none, lambda x: to_class(CanonicalCardClass, x)], x)


def Cardfromdict(s: Any) -> Card:
    return Card.from_dict(s)


def Cardtodict(x: Card) -> Any:
    return to_class(Card, x)


def CardTypefromdict(s: Any) -> CardType:
    return CardType(s)


def CardTypetodict(x: CardType) -> Any:
    return to_enum(CardType, x)


def FilterSettingsfromdict(s: Any) -> FilterSettings:
    return FilterSettings.from_dict(s)


def FilterSettingstodict(x: FilterSettings) -> Any:
    return to_class(FilterSettings, x)


def Gamefromdict(s: Any) -> Game:
    return Game(s)


def Gametodict(x: Game) -> Any:
    return to_enum(Game, x)


def ImportSitefromdict(s: Any) -> ImportSite:
    return ImportSite.from_dict(s)


def ImportSitetodict(x: ImportSite) -> Any:
    return to_class(ImportSite, x)


def Languagefromdict(s: Any) -> Language:
    return Language.from_dict(s)


def Languagetodict(x: Language) -> Any:
    return to_class(Language, x)


def ModerationDriveItemfromdict(s: Any) -> ModerationDriveItem:
    return ModerationDriveItem.from_dict(s)


def ModerationDriveItemtodict(x: ModerationDriveItem) -> Any:
    return to_class(ModerationDriveItem, x)


def ModerationQueueItemfromdict(s: Any) -> ModerationQueueItem:
    return ModerationQueueItem.from_dict(s)


def ModerationQueueItemtodict(x: ModerationQueueItem) -> Any:
    return to_class(ModerationQueueItem, x)


def NewCardsFirstPagefromdict(s: Any) -> NewCardsFirstPage:
    return NewCardsFirstPage.from_dict(s)


def NewCardsFirstPagetodict(x: NewCardsFirstPage) -> Any:
    return to_class(NewCardsFirstPage, x)


def PrintingCandidatefromdict(s: Any) -> PrintingCandidate:
    return PrintingCandidate.from_dict(s)


def PrintingCandidatetodict(x: PrintingCandidate) -> Any:
    return to_class(PrintingCandidate, x)


def PrintingTagStatusfromdict(s: Any) -> PrintingTagStatus:
    return PrintingTagStatus(s)


def PrintingTagStatustodict(x: PrintingTagStatus) -> Any:
    return to_enum(PrintingTagStatus, x)


def QuestionFeedCountsfromdict(s: Any) -> QuestionFeedCounts:
    return QuestionFeedCounts.from_dict(s)


def QuestionFeedCountstodict(x: QuestionFeedCounts) -> Any:
    return to_class(QuestionFeedCounts, x)


def QuestionFeedItemfromdict(s: Any) -> QuestionFeedItem:
    return QuestionFeedItem.from_dict(s)


def QuestionFeedItemtodict(x: QuestionFeedItem) -> Any:
    return to_class(QuestionFeedItem, x)


def QuestionFeedResponsefromdict(s: Any) -> QuestionFeedResponse:
    return QuestionFeedResponse.from_dict(s)


def QuestionFeedResponsetodict(x: QuestionFeedResponse) -> Any:
    return to_class(QuestionFeedResponse, x)


def SearchQueryfromdict(s: Any) -> SearchQuery:
    return SearchQuery.from_dict(s)


def SearchQuerytodict(x: SearchQuery) -> Any:
    return to_class(SearchQuery, x)


def SearchSettingsfromdict(s: Any) -> SearchSettings:
    return SearchSettings.from_dict(s)


def SearchSettingstodict(x: SearchSettings) -> Any:
    return to_class(SearchSettings, x)


def SearchTypeSettingsfromdict(s: Any) -> SearchTypeSettings:
    return SearchTypeSettings.from_dict(s)


def SearchTypeSettingstodict(x: SearchTypeSettings) -> Any:
    return to_class(SearchTypeSettings, x)


def SortByfromdict(s: Any) -> SortBy:
    return SortBy(s)


def SortBytodict(x: SortBy) -> Any:
    return to_enum(SortBy, x)


def Sourcefromdict(s: Any) -> Source:
    return Source.from_dict(s)


def Sourcetodict(x: Source) -> Any:
    return to_class(Source, x)


def SourceContributionfromdict(s: Any) -> SourceContribution:
    return SourceContribution.from_dict(s)


def SourceContributiontodict(x: SourceContribution) -> Any:
    return to_class(SourceContribution, x)


def SourceRowfromdict(s: Any) -> List[Union[int, bool]]:
    return from_list(lambda x: from_union([from_int, from_bool], x), s)


def SourceRowtodict(x: List[Union[int, bool]]) -> Any:
    return from_list(lambda x: from_union([from_int, from_bool], x), x)


def SourceSettingsfromdict(s: Any) -> SourceSettings:
    return SourceSettings.from_dict(s)


def SourceSettingstodict(x: SourceSettings) -> Any:
    return to_class(SourceSettings, x)


def SourceTypefromdict(s: Any) -> SourceType:
    return SourceType(s)


def SourceTypetodict(x: SourceType) -> Any:
    return to_enum(SourceType, x)


def Supporterfromdict(s: Any) -> Supporter:
    return Supporter.from_dict(s)


def Supportertodict(x: Supporter) -> Any:
    return to_class(Supporter, x)


def SupporterTierfromdict(s: Any) -> SupporterTier:
    return SupporterTier.from_dict(s)


def SupporterTiertodict(x: SupporterTier) -> Any:
    return to_class(SupporterTier, x)


def Tagfromdict(s: Any) -> Tag:
    return Tag.from_dict(s)


def Tagtodict(x: Tag) -> Any:
    return to_class(Tag, x)


def TagConsensusEntryfromdict(s: Any) -> TagConsensusEntry:
    return TagConsensusEntry.from_dict(s)


def TagConsensusEntrytodict(x: TagConsensusEntry) -> Any:
    return to_class(TagConsensusEntry, x)


def TagVoteTallyEntryfromdict(s: Any) -> TagVoteTallyEntry:
    return TagVoteTallyEntry.from_dict(s)


def TagVoteTallyEntrytodict(x: TagVoteTallyEntry) -> Any:
    return to_class(TagVoteTallyEntry, x)


def VoteQueueItemfromdict(s: Any) -> VoteQueueItem:
    return VoteQueueItem.from_dict(s)


def VoteQueueItemtodict(x: VoteQueueItem) -> Any:
    return to_class(VoteQueueItem, x)


def VoteTallyEntryfromdict(s: Any) -> VoteTallyEntry:
    return VoteTallyEntry.from_dict(s)


def VoteTallyEntrytodict(x: VoteTallyEntry) -> Any:
    return to_class(VoteTallyEntry, x)


def ArtistCandidatesRequestfromdict(s: Any) -> ArtistCandidatesRequest:
    return ArtistCandidatesRequest.from_dict(s)


def ArtistCandidatesRequesttodict(x: ArtistCandidatesRequest) -> Any:
    return to_class(ArtistCandidatesRequest, x)


def ArtistCandidatesResponsefromdict(s: Any) -> ArtistCandidatesResponse:
    return ArtistCandidatesResponse.from_dict(s)


def ArtistCandidatesResponsetodict(x: ArtistCandidatesResponse) -> Any:
    return to_class(ArtistCandidatesResponse, x)


def ArtistConsensusRequestfromdict(s: Any) -> ArtistConsensusRequest:
    return ArtistConsensusRequest.from_dict(s)


def ArtistConsensusRequesttodict(x: ArtistConsensusRequest) -> Any:
    return to_class(ArtistConsensusRequest, x)


def ArtistConsensusResponsefromdict(s: Any) -> ArtistConsensusResponse:
    return ArtistConsensusResponse.from_dict(s)


def ArtistConsensusResponsetodict(x: ArtistConsensusResponse) -> Any:
    return to_class(ArtistConsensusResponse, x)


def CardbacksRequestfromdict(s: Any) -> CardbacksRequest:
    return CardbacksRequest.from_dict(s)


def CardbacksRequesttodict(x: CardbacksRequest) -> Any:
    return to_class(CardbacksRequest, x)


def CardbacksResponsefromdict(s: Any) -> CardbacksResponse:
    return CardbacksResponse.from_dict(s)


def CardbacksResponsetodict(x: CardbacksResponse) -> Any:
    return to_class(CardbacksResponse, x)


def CardsRequestfromdict(s: Any) -> CardsRequest:
    return CardsRequest.from_dict(s)


def CardsRequesttodict(x: CardsRequest) -> Any:
    return to_class(CardsRequest, x)


def CardsResponsefromdict(s: Any) -> CardsResponse:
    return CardsResponse.from_dict(s)


def CardsResponsetodict(x: CardsResponse) -> Any:
    return to_class(CardsResponse, x)


def ContributionsResponsefromdict(s: Any) -> ContributionsResponse:
    return ContributionsResponse.from_dict(s)


def ContributionsResponsetodict(x: ContributionsResponse) -> Any:
    return to_class(ContributionsResponse, x)


def DFCPairsResponsefromdict(s: Any) -> DFCPairsResponse:
    return DFCPairsResponse.from_dict(s)


def DFCPairsResponsetodict(x: DFCPairsResponse) -> Any:
    return to_class(DFCPairsResponse, x)


def EditorSearchRequestfromdict(s: Any) -> EditorSearchRequest:
    return EditorSearchRequest.from_dict(s)


def EditorSearchRequesttodict(x: EditorSearchRequest) -> Any:
    return to_class(EditorSearchRequest, x)


def EditorSearchResponsefromdict(s: Any) -> EditorSearchResponse:
    return EditorSearchResponse.from_dict(s)


def EditorSearchResponsetodict(x: EditorSearchResponse) -> Any:
    return to_class(EditorSearchResponse, x)


def ErrorResponsefromdict(s: Any) -> ErrorResponse:
    return ErrorResponse.from_dict(s)


def ErrorResponsetodict(x: ErrorResponse) -> Any:
    return to_class(ErrorResponse, x)


def ExploreSearchRequestfromdict(s: Any) -> ExploreSearchRequest:
    return ExploreSearchRequest.from_dict(s)


def ExploreSearchRequesttodict(x: ExploreSearchRequest) -> Any:
    return to_class(ExploreSearchRequest, x)


def ExploreSearchResponsefromdict(s: Any) -> ExploreSearchResponse:
    return ExploreSearchResponse.from_dict(s)


def ExploreSearchResponsetodict(x: ExploreSearchResponse) -> Any:
    return to_class(ExploreSearchResponse, x)


def ImportSiteDecklistRequestfromdict(s: Any) -> ImportSiteDecklistRequest:
    return ImportSiteDecklistRequest.from_dict(s)


def ImportSiteDecklistRequesttodict(x: ImportSiteDecklistRequest) -> Any:
    return to_class(ImportSiteDecklistRequest, x)


def ImportSiteDecklistResponsefromdict(s: Any) -> ImportSiteDecklistResponse:
    return ImportSiteDecklistResponse.from_dict(s)


def ImportSiteDecklistResponsetodict(x: ImportSiteDecklistResponse) -> Any:
    return to_class(ImportSiteDecklistResponse, x)


def ImportSitesResponsefromdict(s: Any) -> ImportSitesResponse:
    return ImportSitesResponse.from_dict(s)


def ImportSitesResponsetodict(x: ImportSitesResponse) -> Any:
    return to_class(ImportSitesResponse, x)


def InfoResponsefromdict(s: Any) -> InfoResponse:
    return InfoResponse.from_dict(s)


def InfoResponsetodict(x: InfoResponse) -> Any:
    return to_class(InfoResponse, x)


def LanguagesResponsefromdict(s: Any) -> LanguagesResponse:
    return LanguagesResponse.from_dict(s)


def LanguagesResponsetodict(x: LanguagesResponse) -> Any:
    return to_class(LanguagesResponse, x)


def ModerationDriveCardsRequestfromdict(s: Any) -> ModerationDriveCardsRequest:
    return ModerationDriveCardsRequest.from_dict(s)


def ModerationDriveCardsRequesttodict(x: ModerationDriveCardsRequest) -> Any:
    return to_class(ModerationDriveCardsRequest, x)


def ModerationDriveCardsResponsefromdict(s: Any) -> ModerationDriveCardsResponse:
    return ModerationDriveCardsResponse.from_dict(s)


def ModerationDriveCardsResponsetodict(x: ModerationDriveCardsResponse) -> Any:
    return to_class(ModerationDriveCardsResponse, x)


def ModerationDrivesRequestfromdict(s: Any) -> ModerationDrivesRequest:
    return ModerationDrivesRequest.from_dict(s)


def ModerationDrivesRequesttodict(x: ModerationDrivesRequest) -> Any:
    return to_class(ModerationDrivesRequest, x)


def ModerationDrivesResponsefromdict(s: Any) -> ModerationDrivesResponse:
    return ModerationDrivesResponse.from_dict(s)


def ModerationDrivesResponsetodict(x: ModerationDrivesResponse) -> Any:
    return to_class(ModerationDrivesResponse, x)


def ModerationQueueRequestfromdict(s: Any) -> ModerationQueueRequest:
    return ModerationQueueRequest.from_dict(s)


def ModerationQueueRequesttodict(x: ModerationQueueRequest) -> Any:
    return to_class(ModerationQueueRequest, x)


def ModerationQueueResponsefromdict(s: Any) -> ModerationQueueResponse:
    return ModerationQueueResponse.from_dict(s)


def ModerationQueueResponsetodict(x: ModerationQueueResponse) -> Any:
    return to_class(ModerationQueueResponse, x)


def ModerationRemoveCardRequestfromdict(s: Any) -> ModerationRemoveCardRequest:
    return ModerationRemoveCardRequest.from_dict(s)


def ModerationRemoveCardRequesttodict(x: ModerationRemoveCardRequest) -> Any:
    return to_class(ModerationRemoveCardRequest, x)


def ModerationRemoveCardResponsefromdict(s: Any) -> ModerationRemoveCardResponse:
    return ModerationRemoveCardResponse.from_dict(s)


def ModerationRemoveCardResponsetodict(x: ModerationRemoveCardResponse) -> Any:
    return to_class(ModerationRemoveCardResponse, x)


def ModerationRemoveDriveRequestfromdict(s: Any) -> ModerationRemoveDriveRequest:
    return ModerationRemoveDriveRequest.from_dict(s)


def ModerationRemoveDriveRequesttodict(x: ModerationRemoveDriveRequest) -> Any:
    return to_class(ModerationRemoveDriveRequest, x)


def ModerationRemoveDriveResponsefromdict(s: Any) -> ModerationRemoveDriveResponse:
    return ModerationRemoveDriveResponse.from_dict(s)


def ModerationRemoveDriveResponsetodict(x: ModerationRemoveDriveResponse) -> Any:
    return to_class(ModerationRemoveDriveResponse, x)


def NewCardsFirstPagesResponsefromdict(s: Any) -> NewCardsFirstPagesResponse:
    return NewCardsFirstPagesResponse.from_dict(s)


def NewCardsFirstPagesResponsetodict(x: NewCardsFirstPagesResponse) -> Any:
    return to_class(NewCardsFirstPagesResponse, x)


def NewCardsPageResponsefromdict(s: Any) -> NewCardsPageResponse:
    return NewCardsPageResponse.from_dict(s)


def NewCardsPageResponsetodict(x: NewCardsPageResponse) -> Any:
    return to_class(NewCardsPageResponse, x)


def OldEditorSearchRequestfromdict(s: Any) -> OldEditorSearchRequest:
    return OldEditorSearchRequest.from_dict(s)


def OldEditorSearchRequesttodict(x: OldEditorSearchRequest) -> Any:
    return to_class(OldEditorSearchRequest, x)


def OldEditorSearchResponsefromdict(s: Any) -> OldEditorSearchResponse:
    return OldEditorSearchResponse.from_dict(s)


def OldEditorSearchResponsetodict(x: OldEditorSearchResponse) -> Any:
    return to_class(OldEditorSearchResponse, x)


def PatreonResponsefromdict(s: Any) -> PatreonResponse:
    return PatreonResponse.from_dict(s)


def PatreonResponsetodict(x: PatreonResponse) -> Any:
    return to_class(PatreonResponse, x)


def PrintingCandidatesRequestfromdict(s: Any) -> PrintingCandidatesRequest:
    return PrintingCandidatesRequest.from_dict(s)


def PrintingCandidatesRequesttodict(x: PrintingCandidatesRequest) -> Any:
    return to_class(PrintingCandidatesRequest, x)


def PrintingCandidatesResponsefromdict(s: Any) -> PrintingCandidatesResponse:
    return PrintingCandidatesResponse.from_dict(s)


def PrintingCandidatesResponsetodict(x: PrintingCandidatesResponse) -> Any:
    return to_class(PrintingCandidatesResponse, x)


def PrintingConsensusRequestfromdict(s: Any) -> PrintingConsensusRequest:
    return PrintingConsensusRequest.from_dict(s)


def PrintingConsensusRequesttodict(x: PrintingConsensusRequest) -> Any:
    return to_class(PrintingConsensusRequest, x)


def PrintingConsensusResponsefromdict(s: Any) -> PrintingConsensusResponse:
    return PrintingConsensusResponse.from_dict(s)


def PrintingConsensusResponsetodict(x: PrintingConsensusResponse) -> Any:
    return to_class(PrintingConsensusResponse, x)


def PrintingTagQueueResponsefromdict(s: Any) -> PrintingTagQueueResponse:
    return PrintingTagQueueResponse.from_dict(s)


def PrintingTagQueueResponsetodict(x: PrintingTagQueueResponse) -> Any:
    return to_class(PrintingTagQueueResponse, x)


def ReportCardRequestfromdict(s: Any) -> ReportCardRequest:
    return ReportCardRequest.from_dict(s)


def ReportCardRequesttodict(x: ReportCardRequest) -> Any:
    return to_class(ReportCardRequest, x)


def ReportCardResponsefromdict(s: Any) -> ReportCardResponse:
    return ReportCardResponse.from_dict(s)


def ReportCardResponsetodict(x: ReportCardResponse) -> Any:
    return to_class(ReportCardResponse, x)


def SampleCardsResponsefromdict(s: Any) -> SampleCardsResponse:
    return SampleCardsResponse.from_dict(s)


def SampleCardsResponsetodict(x: SampleCardsResponse) -> Any:
    return to_class(SampleCardsResponse, x)


def SearchEngineHealthResponsefromdict(s: Any) -> SearchEngineHealthResponse:
    return SearchEngineHealthResponse.from_dict(s)


def SearchEngineHealthResponsetodict(x: SearchEngineHealthResponse) -> Any:
    return to_class(SearchEngineHealthResponse, x)


def SourcesResponsefromdict(s: Any) -> SourcesResponse:
    return SourcesResponse.from_dict(s)


def SourcesResponsetodict(x: SourcesResponse) -> Any:
    return to_class(SourcesResponse, x)


def SubmitArtistVoteRequestfromdict(s: Any) -> SubmitArtistVoteRequest:
    return SubmitArtistVoteRequest.from_dict(s)


def SubmitArtistVoteRequesttodict(x: SubmitArtistVoteRequest) -> Any:
    return to_class(SubmitArtistVoteRequest, x)


def SubmitPrintingTagRequestfromdict(s: Any) -> SubmitPrintingTagRequest:
    return SubmitPrintingTagRequest.from_dict(s)


def SubmitPrintingTagRequesttodict(x: SubmitPrintingTagRequest) -> Any:
    return to_class(SubmitPrintingTagRequest, x)


def SubmitTagVoteRequestfromdict(s: Any) -> SubmitTagVoteRequest:
    return SubmitTagVoteRequest.from_dict(s)


def SubmitTagVoteRequesttodict(x: SubmitTagVoteRequest) -> Any:
    return to_class(SubmitTagVoteRequest, x)


def TagConsensusRequestfromdict(s: Any) -> TagConsensusRequest:
    return TagConsensusRequest.from_dict(s)


def TagConsensusRequesttodict(x: TagConsensusRequest) -> Any:
    return to_class(TagConsensusRequest, x)


def TagConsensusResponsefromdict(s: Any) -> TagConsensusResponse:
    return TagConsensusResponse.from_dict(s)


def TagConsensusResponsetodict(x: TagConsensusResponse) -> Any:
    return to_class(TagConsensusResponse, x)


def TagsResponsefromdict(s: Any) -> TagsResponse:
    return TagsResponse.from_dict(s)


def TagsResponsetodict(x: TagsResponse) -> Any:
    return to_class(TagsResponse, x)


def VoteQueueRequestfromdict(s: Any) -> VoteQueueRequest:
    return VoteQueueRequest.from_dict(s)


def VoteQueueRequesttodict(x: VoteQueueRequest) -> Any:
    return to_class(VoteQueueRequest, x)


def VoteQueueResponsefromdict(s: Any) -> VoteQueueResponse:
    return VoteQueueResponse.from_dict(s)


def VoteQueueResponsetodict(x: VoteQueueResponse) -> Any:
    return to_class(VoteQueueResponse, x)


def WhoamiResponsefromdict(s: Any) -> WhoamiResponse:
    return WhoamiResponse.from_dict(s)


def WhoamiResponsetodict(x: WhoamiResponse) -> Any:
    return to_class(WhoamiResponse, x)
