from django.urls import path

from . import views

urlpatterns = [
    path("2/editorSearch/", views.old_post_editor_search),
    path("3/editorSearch/", views.post_editor_search),
    path("2/exploreSearch/", views.post_explore_search),
    path("2/cards/", views.post_cards),
    path("2/sources/", views.get_sources),
    path("2/DFCPairs/", views.get_dfc_pairs),
    path("2/languages/", views.get_languages),
    path("2/tags/", views.get_tags),
    path("2/cardbacks/", views.post_cardbacks),
    path("2/importSites/", views.get_import_sites),
    path("2/importSiteDecklist/", views.post_import_site_decklist),
    path("2/sampleCards/", views.get_sample_cards),
    path("2/contributions/", views.get_contributions),
    path("2/newCardsFirstPages/", views.get_new_cards_first_pages),
    path("2/newCardsPage/", views.get_new_cards_page),
    path("2/info/", views.get_info),
    path("2/patreon/", views.get_patreon),
    path("2/searchEngineHealth/", views.get_search_engine_health),
    path("2/localFileImage/", views.get_local_file_image),
    path("2/printingCandidates/", views.post_printing_candidates),
    path("2/printingConsensus/", views.post_printing_consensus),
    path("2/submitPrintingTag/", views.post_submit_printing_tag),
    path("2/printingTagQueue/", views.get_printing_tag_queue),
    path("2/artistCandidates/", views.post_artist_candidates),
    path("2/artistConsensus/", views.post_artist_consensus),
    path("2/submitArtistVote/", views.post_submit_artist_vote),
    path("2/tagConsensus/", views.post_tag_consensus),
    path("2/submitTagVote/", views.post_submit_tag_vote),
    path("2/voteQueue/", views.post_vote_queue),
    path("2/moderationQueue/", views.post_moderation_queue),
    path("2/moderationDrives/", views.post_moderation_drives),
    path("2/moderationDriveCards/", views.post_moderation_drive_cards),
    path("2/moderationRemoveCard/", views.post_moderation_remove_card),
    path("2/moderationRemoveDrive/", views.post_moderation_remove_drive),
    path("2/reviewClusters/", views.post_review_cluster_list),
    path("2/reviewClusterDetail/", views.post_review_cluster_detail),
    path("2/confirmReviewCluster/", views.post_confirm_review_cluster),
    path("2/questionFeed/", views.get_question_feed),
    path("2/reportCard/", views.post_report_card),
    path("2/whoami/", views.get_whoami),
    path("2/savedDecks/", views.get_saved_decks),
    path("2/saveDeck/", views.post_save_deck),
    path("2/loadDeck/", views.post_load_deck),
    path("2/deleteDeck/", views.post_delete_deck),
    path("2/cryptoProfile/", views.get_crypto_profile),
    path("2/saveCryptoProfile/", views.post_save_crypto_profile),
    path("2/resetSavedDecks/", views.post_reset_saved_decks),
    path("2/createDeckShare/", views.post_create_deck_share),
    path("2/deckShares/", views.get_deck_shares),
    path("2/revokeDeckShare/", views.post_revoke_deck_share),
    path("2/getSharedDeck/", views.post_get_shared_deck),
]
