"""
Django settings for MPCAutofill project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from typing import Optional

import django_stubs_ext
import environ

django_stubs_ext.monkeypatch()  # https://stackoverflow.com/q/67965529

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Production-specific settings kept in .env, modify the .env.dist then rename
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
env.read_env(os.path.join(BASE_DIR, "MPCAutofill/.env"))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY", default="-")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DJANGO_DEBUG", default=False)

# IP or Domain
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# This server's own public URL, used to build image URLs for LOCAL_FILE sources (the frontend can only
# load images by URL, so images on disk are served back out through this server's own `get_local_file_image` view).
LOCAL_FILE_SOURCE_BASE_URL = env("LOCAL_FILE_SOURCE_BASE_URL", default="http://localhost:8000")

# Unique site information
GTAG = env("GTAG", default="")  # Google Analytics
SITE_NAME = env("SITE_NAME", default="MPC Autofill")
TARGET_EMAIL = env("TARGET_EMAIL", default="your_email@somewhere.com")
DISCORD = env("DISCORD", default="https://discord.gg/magicproxies")
REDDIT = env("REDDIT", default="https://www.reddit.com/r/mpcproxies/")
THEME = env("THEME", default="superhero")
DESCRIPTION = env("DESCRIPTION", default="")

# Integration secrets
MOXFIELD_SECRET: Optional[str] = env("MOXFIELD_SECRET", default=None)

PREPEND_WWW = env("PREPEND_WWW", default=False)

# Printing-aware card tagging consensus thresholds. See cardpicker.printing_consensus.
PRINTING_TAG_MIN_VOTES = env.float("PRINTING_TAG_MIN_VOTES", default=2)
PRINTING_TAG_MIN_SHARE = env.float("PRINTING_TAG_MIN_SHARE", default=0.6)
PRINTING_TAG_ADMIN_WEIGHT = env.float("PRINTING_TAG_ADMIN_WEIGHT", default=5)
PRINTING_TAG_AI_WEIGHT = env.float("PRINTING_TAG_AI_WEIGHT", default=0.5)
# weight of a vote cast by a privileged user (a Moderators-group member - see
# cardpicker.moderation.privileged_weight). Defaults to the admin weight: a lone moderator
# clears the consensus threshold the same way a lone admin does.
VOTE_PRIVILEGED_WEIGHT = env.float("VOTE_PRIVILEGED_WEIGHT", default=PRINTING_TAG_ADMIN_WEIGHT)
# federation-readiness stub (see docs/federation-v1.md) - no import path creates federated
# votes yet, so this setting is currently inert, but it's wired into vote_consensus._SOURCE_WEIGHTS
# alongside the weights above.
VOTE_FEDERATED_WEIGHT = env.float("VOTE_FEDERATED_WEIGHT", default=1.0)
# django-ratelimit rate string (see cardpicker.views.post_submit_printing_tag), keyed by the
# client-generated anonymous ID (IP as a fallback if that header is somehow missing).
PRINTING_TAG_SUBMISSION_RATE = env("PRINTING_TAG_SUBMISSION_RATE", default="20/h")

# Fuzzy tag-matching confidence thresholds. See cardpicker.tags.Tags.match_tag_fuzzy.
TAG_MATCH_HIGH_CONFIDENCE_THRESHOLD = env.float("TAG_MATCH_HIGH_CONFIDENCE_THRESHOLD", default=0.92)
TAG_MATCH_LOW_CONFIDENCE_THRESHOLD = env.float("TAG_MATCH_LOW_CONFIDENCE_THRESHOLD", default=0.6)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = env(
    "CSRF_TRUSTED_ORIGINS",
    default=[
        "http://localhost",
        "http://127.0.0.1",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ],
)  # required for Docker with Django 4.x+

# Application definition

INSTALLED_APPS = [
    "cardpicker.apps.CardpickerConfig",
    "accounts",
    "django_q",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "django_elasticsearch_dsl",
    "corsheaders",
    # Discord moderator auth - see the "Discord moderator auth" settings block below. The
    # provider app itself ("allauth.socialaccount.providers.discord") is appended there only
    # when credentials are configured, so an instance without them runs with allauth installed
    # but no way to log in through it.
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # mandatory for django-allauth >= 0.56
]

CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    # allow CORS from a frontend app running locally and from the deployed frontend
    default=[
        "http://127.0.0.1",
        "http://127.0.0.1:3000",
        "http://localhost",
        "http://localhost:3000",
        "https://proxyprints.ca",
        "https://proxyprints.github.io",
    ],
)

# Discord moderator auth (django-allauth). Only moderators ever log in - ordinary voters stay
# on the client-generated anonymous_id scheme, untouched. Logging in grants nothing by itself:
# a user becomes a moderator only when an admin adds them to the MODERATORS_GROUP_NAME group
# (see docs/features/moderation.md for the one-time setup). With no credentials configured
# (e.g. dev), the provider app is simply not installed: /accounts/discord/login/ 404s, the
# whoami endpoint reports discordEnabled=false, and nothing crashes.
DISCORD_CLIENT_ID = env("DISCORD_CLIENT_ID", default="")
DISCORD_CLIENT_SECRET = env("DISCORD_CLIENT_SECRET", default="")
DISCORD_AUTH_ENABLED = bool(DISCORD_CLIENT_ID and DISCORD_CLIENT_SECRET)
if DISCORD_AUTH_ENABLED:
    INSTALLED_APPS.append("allauth.socialaccount.providers.discord")
    # App-in-settings configuration - no SocialApp DB row (and no django.contrib.sites) needed.
    SOCIALACCOUNT_PROVIDERS = {"discord": {"APPS": [{"client_id": DISCORD_CLIENT_ID, "secret": DISCORD_CLIENT_SECRET}]}}
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Django admin login, unchanged
    "allauth.account.auth_backends.AuthenticationBackend",
]
ACCOUNT_EMAIL_VERIFICATION = "none"  # Discord is the identity authority; no verification emails
SOCIALACCOUNT_AUTO_SIGNUP = True  # first Discord login auto-creates the Django user
# Keep allauth's confirmation interstitial on the login link (default-secure; costs one click).
SOCIALACCOUNT_LOGIN_ON_GET = False
# Logout via a plain link so it can round-trip back to the frontend with ?next=. The tradeoff
# (a hostile page could force-logout a moderator - a nuisance, not an escalation) is documented
# in docs/features/moderation.md.
ACCOUNT_LOGOUT_ON_GET = True
# Allows ?next= redirects back to the frontend origin - see accounts.adapter.
ACCOUNT_ADAPTER = "accounts.adapter.FrontendRedirectAccountAdapter"
# The Django auth group whose members count as moderators (see cardpicker.moderation). A
# setting rather than a hardcoded string so a future grant mechanism (e.g. syncing membership
# from a Discord guild role) only has to manage this one group.
MODERATORS_GROUP_NAME = env("MODERATORS_GROUP_NAME", default="Moderators")

# The moderator session cookie must round-trip from the cross-site frontend origin
# (github.io <-> api.proxyprints.ca), which requires SameSite=None + Secure in production -
# set via env there. Defaults suit local dev: localhost:3000 -> localhost:8000 is same-site,
# so Lax cookies flow over plain http.
SESSION_COOKIE_SAMESITE = env("SESSION_COOKIE_SAMESITE", default="Lax")
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)
# Lets browsers attach credentials (the session cookie) to CORS requests from the explicit
# allowlist above. Only fetches that opt in with credentials:'include' are affected;
# anonymous traffic is byte-identical.
CORS_ALLOW_CREDENTIALS = env.bool("CORS_ALLOW_CREDENTIALS", default=True)

ROOT_URLCONF = "MPCAutofill.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "MPCAutofill.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": env("DATABASE_ENGINE", default="django.db.backends.postgresql"),
        "NAME": env("DATABASE_NAME", default="mpcautofill"),
        "USER": env("DATABASE_USER", default="mpcautofill"),
        "PASSWORD": env("DATABASE_PASSWORD", default="mpcautofill"),
        "HOST": env("DATABASE_HOST", default="localhost"),
        "PORT": env("DATABASE_PORT", default=5432),
    }
}
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = env("LANG_CODE", default="en-us")

TIME_ZONE = env("TIME_ZONE", default="America/New_York")

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_URL = "/" + env("STATIC", default="static") + "/"
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

STATICFILES_DIRS = [
    os.path.normpath(os.path.join(BASE_DIR, "cardpicker/static")),
]

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), env("STATIC", default="static"))

# elasticsearch DSL settings
ELASTICSEARCH_HOST = env("ELASTICSEARCH_HOST", default="localhost")
ELASTICSEARCH_PORT = env("ELASTICSEARCH_PORT", default="9200")
ELASTICSEARCH_DSL = {
    "default": {"hosts": f"{ELASTICSEARCH_HOST}:{ELASTICSEARCH_PORT}"},
}

ELASTICSEARCH_DSL_AUTOSYNC = False

# Email for logging
ADMINS = [("admin", env("TARGET_EMAIL", default=""))]
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = env("DJANGO_GMAIL", default="")
EMAIL_HOST_PASSWORD = env("DJANGO_GMAIL_PASSWORD", default="")
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "default from email"

# Database update settings
DEFAULT_CARDBACK_FOLDER_PATH = env("DEFAULT_CARDBACK_FOLDER_PATH", default="Chilli_Axe's MTG Renders / 12. Cardbacks")
DEFAULT_CARDBACK_IMAGE_NAME = env("DEFAULT_CARDBACK_IMAGE_NAME", default="Black Lotus")

# Game integration - see integrations.py for valid options
GAME = env("GAME", default="")

# PATREON
PATREON_ACCESS = env("PATREON_ACCESS", default="")
PATREON_REFRESH = env("PATREON_REFRESH", default="")
PATREON_CLIENT = env("PATREON_CLIENT", default="")
PATREON_SECRET = env("PATREON_SECRET", default="")
PATREON_URL = env("PATREON_URL", default="")

# django-q2
Q_CLUSTER = {
    "name": "DjangoORM",
    "workers": 8,
    "recycle": 500,
    "timeout": 60 * 60 * 12,  # 12 hours - extreme upper limit
    "retry": 60 * 60 * 12 + 1,  # must be longer than timeout
    "max_attempts": 1,
    "compress": True,
    "save_limit": 250,
    "queue_limit": 500,
    "cpu_affinity": 1,
    "label": "Django Q2",
    "orm": "default",
}
