"""
Django settings for MPCAutofill project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from typing import Optional

import django_stubs_ext
import environ

django_stubs_ext.monkeypatch()  # https://stackoverflow.com/q/67965529

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Production-specific settings kept in .env, modify the .env.dist then rename
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
env.read_env(os.path.join(BASE_DIR, "MPCAutofill/.env"))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY", default="-")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DJANGO_DEBUG", default=False)

# IP or Domain
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# nginx terminates TLS and proxies to this container over plain HTTP (see docker/nginx/nginx.conf,
# which forwards X-Forwarded-Proto) - without this, request.is_secure() always reads False here,
# so anything building an absolute URL from the request (django-allauth's OAuth redirect_uri,
# notably) constructs an http:// URL even though the real, public-facing request was https://.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# This server's own public URL, used to build image URLs for LOCAL_FILE sources (the frontend can only
# load images by URL, so images on disk are served back out through this server's own `get_local_file_image` view).
LOCAL_FILE_SOURCE_BASE_URL = env("LOCAL_FILE_SOURCE_BASE_URL", default="http://localhost:8000")

# Unique site information
GTAG = env("GTAG", default="")  # Google Analytics
SITE_NAME = env("SITE_NAME", default="MPC Autofill")
TARGET_EMAIL = env("TARGET_EMAIL", default="your_email@somewhere.com")
DISCORD = env("DISCORD", default="https://discord.gg/magicproxies")
REDDIT = env("REDDIT", default="https://www.reddit.com/r/mpcproxies/")
THEME = env("THEME", default="superhero")
DESCRIPTION = env("DESCRIPTION", default="")

# Integration secrets
MOXFIELD_SECRET: Optional[str] = env("MOXFIELD_SECRET", default=None)

PREPEND_WWW = env("PREPEND_WWW", default=False)

# Printing-aware card tagging consensus thresholds. See cardpicker.printing_consensus.
PRINTING_TAG_MIN_VOTES = env.float("PRINTING_TAG_MIN_VOTES", default=2)
PRINTING_TAG_MIN_SHARE = env.float("PRINTING_TAG_MIN_SHARE", default=0.6)
PRINTING_TAG_ADMIN_WEIGHT = env.float("PRINTING_TAG_ADMIN_WEIGHT", default=5)
PRINTING_TAG_MACHINE_WEIGHT = env.float("PRINTING_TAG_MACHINE_WEIGHT", default=0.5)
# weight of a vote cast by a privileged user (a Moderators-group member - see
# cardpicker.moderation.privileged_weight). Defaults to the admin weight: a lone moderator
# clears the consensus threshold the same way a lone admin does.
VOTE_PRIVILEGED_WEIGHT = env.float("VOTE_PRIVILEGED_WEIGHT", default=PRINTING_TAG_ADMIN_WEIGHT)
# federation-readiness stub (see docs/federation-v1.md) - no import path creates federated
# votes yet, so this setting is currently inert, but it's wired into vote_consensus._SOURCE_WEIGHTS
# alongside the weights above.
VOTE_FEDERATED_WEIGHT = env.float("VOTE_FEDERATED_WEIGHT", default=1.0)
# Per-vote weight of a VoteSource.IMPLICIT vote (docs/features/printing-tags.md's implicit-vote
# section - the /editor filter-chip signal cast when a person picks a card while chips are
# active). Deliberately tiny relative to a real USER vote (1.0) - this is a passive by-product
# of a selection, not a deliberate tag confirmation. See vote_consensus._SOURCE_WEIGHTS.
PRINTING_TAG_IMPLICIT_WEIGHT = env.float("PRINTING_TAG_IMPLICIT_WEIGHT", default=0.25)
# Hard ceiling on the SUM of implicit weight counted per (card, tag, polarity) outcome group in
# resolve_weighted_consensus - strictly below PRINTING_TAG_MIN_VOTES (2) by policy, so no volume
# of implicit votes on one side can ever supply a whole group's quorum weight by itself (owner-
# ratified 2026-07-22 vote-weight scenario matrix, decision D5/S3). See
# cardpicker.vote_consensus.resolve_weighted_consensus's own docstring for the full mechanism.
PRINTING_TAG_IMPLICIT_CAP = env.float("PRINTING_TAG_IMPLICIT_CAP", default=1.0)
# Illustration-vote consensus thresholds (see cardpicker.illustration_consensus). Their own
# settings, DEFAULTING TO THE PRINTING VALUES ABOVE - so this changes nothing anywhere today, and
# the illustration bar can later be tuned without moving the printing bar with it. Whether an
# illustration claim deserves a different quorum than a printing claim is genuinely open (it is a
# strictly coarser claim - artwork-to-printing is 1:N - so it is easier to get right, but it also
# does less work once resolved) and there is no data to settle it with yet; these exist so the
# answer, when it arrives, is a config change rather than a code change.
# There is deliberately NO ILLUSTRATION_MACHINE_WEIGHT: a vote's weight is a property of WHO cast
# it and by what method, never of what is being voted on - see
# cardpicker.vote_consensus.resolve_vote_weight's own docstring for that argument in full.
ILLUSTRATION_MIN_VOTES = env.float("ILLUSTRATION_MIN_VOTES", default=PRINTING_TAG_MIN_VOTES)
ILLUSTRATION_MIN_SHARE = env.float("ILLUSTRATION_MIN_SHARE", default=PRINTING_TAG_MIN_SHARE)
# Floor share of served `2/questionFeed/` questions that must come from the "likely-resolve"
# pool (a question one more agreeing human vote would actually resolve, per the real
# `resolve_weighted_consensus` - see cardpicker.question_feed.is_likely_resolve_printing) when
# that pool has supply, per the 2026-07-24 data brief's owner-ratified prioritization ruling.
# Selection-layer only - this setting is never read by vote_consensus.py and changes no vote's
# weight/threshold/gate. See docs/features/printing-tags.md's "Unified question feed" section.
QUESTION_FEED_LIKELY_RESOLVE_MIX_RATIO = env.float("QUESTION_FEED_LIKELY_RESOLVE_MIX_RATIO", default=0.51)

# Relative target-share weights for the three REMAINDER lanes (confirm/contested/cold) -
# `cardpicker.question_feed._remainder_lane_order`'s proportional-fairness policy tries whichever
# lane is furthest below its own weight/total share of a session's remainder history first, so
# confirm's much larger real supply (28,112 machine-suggested cards) never crowds contested/cold
# (500-entry pools each) out of a session entirely, the way a fixed confirm-first order did. Not
# required to sum to any particular total - normalised against their own sum, not against 1.0.
# Chosen defaults (3:2:1 -> roughly 50%/33%/17%), not derived from any existing measurement:
# confirm stays the largest share since a quick suggestion-confirmation is genuinely lower voter
# effort than the other two; contested outweighs cold since resolving a live disagreement is
# higher-value than a totally untouched card. See "Remainder mix policy" in this module's own
# docstring.
QUESTION_FEED_CONFIRM_MIX_WEIGHT = env.float("QUESTION_FEED_CONFIRM_MIX_WEIGHT", default=3.0)
QUESTION_FEED_CONTESTED_MIX_WEIGHT = env.float("QUESTION_FEED_CONTESTED_MIX_WEIGHT", default=2.0)
QUESTION_FEED_COLD_MIX_WEIGHT = env.float("QUESTION_FEED_COLD_MIX_WEIGHT", default=1.0)

# issue #727: per-lane candidate-pool warm cadence (minutes) - each is its own settings-driven
# knob, not one global interval, so lane 1 ("churns with every vote cast, wants minutes") and
# lane 4 ("changes only as the pipeline extracts new evidence, tolerates hours") can be tuned
# independently without a migration or code change. See cardpicker.question_feed_pools's own
# module docstring for the full architecture and cardpicker/migrations/
# 0105_question_feed_pools_schedule.py for the django-q2 Schedule rows these back.
QUESTION_FEED_POOL_WARM_MINUTES_RESOLUTION_IMMINENT = env.int(
    "QUESTION_FEED_POOL_WARM_MINUTES_RESOLUTION_IMMINENT", default=5
)
QUESTION_FEED_POOL_WARM_MINUTES_CONFIRM = env.int("QUESTION_FEED_POOL_WARM_MINUTES_CONFIRM", default=15)
QUESTION_FEED_POOL_WARM_MINUTES_CONTESTED = env.int("QUESTION_FEED_POOL_WARM_MINUTES_CONTESTED", default=60)
QUESTION_FEED_POOL_WARM_MINUTES_COLD = env.int("QUESTION_FEED_POOL_WARM_MINUTES_COLD", default=240)

# Max candidates materialised per lane per sub-kind (printing/artist/tag) at each warm - bounds
# both the cache blob size and the read-time random-offset scan cost. A generous cap, not a
# tuned-to-the-edge number - see cardpicker.question_feed_pools's own module docstring.
QUESTION_FEED_POOL_SIZE = env.int("QUESTION_FEED_POOL_SIZE", default=500)

# django-ratelimit rate string (see cardpicker.views.post_submit_printing_tag), keyed by the
# client-generated anonymous ID (IP as a fallback if that header is somehow missing). Shared
# across printing-tag/artist-vote/tag-vote submission (_printing_tag_rate_limit_key/_rate are
# reused across all three @ratelimit call sites in views.py) - one budget for a session's whole
# voting activity, not per-endpoint. Raised from 20/h to 300/h on 2026-07-17 after a real user
# tripped the old limit in ~7 minutes of genuine rapid tagging - the pilot's own confirmation-
# economy work (85k one-tap questions) makes fast legitimate voting the desired behavior now,
# not something to throttle. 300/h = one tap/12s sustained, still a real wall against naive
# flooding; Sybil defense was never resting on this limit anyway - machine-evidence cross-checks
# and cohort revocation (docs/theory.md's addendum) are the actual layer for that.
PRINTING_TAG_SUBMISSION_RATE = env("PRINTING_TAG_SUBMISSION_RATE", default="300/h")
# same mechanism for the card report button (see cardpicker.views.post_report_card).
CARD_REPORT_RATE = env("CARD_REPORT_RATE", default="10/d")
# Separate, tighter budget for implicit votes (cardpicker.views.post_cast_implicit_vote) - a
# person browsing /editor with filter chips active can generate many implicit votes per minute
# just by paging through candidates, a much higher natural cadence than a deliberate tag tap, so
# this is deliberately its own (lower) rate string rather than sharing PRINTING_TAG_SUBMISSION_RATE.
PRINTING_TAG_IMPLICIT_SUBMISSION_RATE = env("PRINTING_TAG_IMPLICIT_SUBMISSION_RATE", default="60/h")
# Artist write-in autocomplete (cardpicker.views.post_artist_autocomplete) - read-only, public,
# unauthenticated, but keyed by IP rather than a client-generated anonymous_id (no vote is being
# cast, so there's no anonymousId in the request body to key on). A generous per-minute budget
# since this fires on every keystroke of a typeahead field, a much higher natural cadence than a
# deliberate vote submission - deliberately its own setting rather than sharing
# PRINTING_TAG_SUBMISSION_RATE (an hourly budget), which would throttle normal typing.
ARTIST_AUTOCOMPLETE_RATE = env("ARTIST_AUTOCOMPLETE_RATE", default="120/m")
# MTGAC artist external links (cardpicker.views.get_artist_external_links) - read-only, public,
# unauthenticated, cache-only (never calls upstream on this path - see
# cardpicker.artist_external_links's own module docstring), keyed by IP for the same reason as
# ARTIST_AUTOCOMPLETE_RATE above. Fires at most once per card-detail-view/display-rail render
# rather than per keystroke, so a much lower budget than autocomplete's is appropriate.
ARTIST_EXTERNAL_LINKS_RATE = env("ARTIST_EXTERNAL_LINKS_RATE", default="60/m")
# MTGAC bulk export URL (cardpicker.artist_external_links.fetch_bulk_export, run weekly by
# cardpicker.migrations.0093_warm_artist_external_links_weekly_schedule's django-q2 Schedule row -
# see that migration's own docstring). Deliberately defaults to EMPTY, not to the real URL:
# this is self-hostable software, and MTGAC granted bulk-endpoint access (with disclosed rate
# limits - 12 requests/hour bulk, 60/15min single-artist) to THIS project specifically, as a
# favour. An unconditional default would mean every fork/self-hosted instance starts polling
# their endpoint the moment it deploys this code - traffic they never agreed to. Empty/unset
# means "not configured", which means the integration is OFF: warm_artist_external_links no-ops
# cleanly (see that command's own docstring) rather than fetching. One knob, not two - there is
# no separate "enabled" flag, only this URL. The value itself is NOT a secret (public,
# unauthenticated), so setting it is safe to do in a plain env var - see
# docs/features/artist-support-links.md for the value and for why enabling this on a
# self-hosted instance means contacting MTGAC yourself rather than assuming this project's
# permission extends to you.
MTGAC_BULK_URL = env("MTGAC_BULK_URL", default="")

# Saved decks (see docs/proposals/proposal-g-user-accounts-saved-decks.md, decision 4). A
# generous, configurable soft cap on named decks (SavedDeckKind.DECK rows only - snapshot rows
# are deliberately uncapped, see cardpicker.models.SavedDeck) per user. Purely an abuse guard,
# not a storage concern (a deck is ~15-35 KB) - stops a runaway script from becoming a
# moderation problem, not a disk-management knob.
SAVED_DECK_MAX_PER_USER = env.int("SAVED_DECK_MAX_PER_USER", default=100)
# zero-knowledge encryption (see the proposal's §8 amendment) - a defensive floor against a
# buggy/malicious client persisting a weak PBKDF2 iteration count into UserCryptoProfile. The
# spec's own floor is 600,000; this is a settings knob only so it can be raised later without a
# code change, never lowered below what's already been accepted from real users.
SAVED_DECK_MIN_KDF_ITERATIONS = env.int("SAVED_DECK_MIN_KDF_ITERATIONS", default=600_000)
# per-deck share links ("PR-5, post-v1" in the proposal doc) - same abuse-guard reasoning as
# SAVED_DECK_MAX_PER_USER above, scoped per-deck rather than per-user since a share is cheap
# (a frozen ciphertext copy the same size as the deck it snapshots, see cardpicker.models.
# SavedDeckShare) but still shouldn't be creatable without bound.
SAVED_DECK_SHARE_MAX_PER_DECK = env.int("SAVED_DECK_SHARE_MAX_PER_DECK", default=20)

# Fuzzy tag-matching confidence thresholds. See cardpicker.tags.Tags.match_tag_fuzzy.
TAG_MATCH_HIGH_CONFIDENCE_THRESHOLD = env.float("TAG_MATCH_HIGH_CONFIDENCE_THRESHOLD", default=0.92)
TAG_MATCH_LOW_CONFIDENCE_THRESHOLD = env.float("TAG_MATCH_LOW_CONFIDENCE_THRESHOLD", default=0.6)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = env(
    "CSRF_TRUSTED_ORIGINS",
    default=[
        "http://localhost",
        "http://127.0.0.1",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ],
)  # required for Docker with Django 4.x+

# Application definition

INSTALLED_APPS = [
    "cardpicker.apps.CardpickerConfig",
    "accounts",
    "django_q",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "django_elasticsearch_dsl",
    "corsheaders",
    # Discord moderator auth - see the "Discord moderator auth" settings block below. The
    # provider app itself ("allauth.socialaccount.providers.discord") is appended there only
    # when credentials are configured, so an instance without them runs with allauth installed
    # but no way to log in through it.
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # mandatory for django-allauth >= 0.56
]

CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    # allow CORS from a frontend app running locally and from the deployed frontend
    default=[
        "http://127.0.0.1",
        "http://127.0.0.1:3000",
        "http://localhost",
        "http://localhost:3000",
        "https://proxyprints.ca",
        "https://proxyprints.github.io",
    ],
)

# Discord moderator auth (django-allauth). Only moderators ever log in - ordinary voters stay
# on the client-generated anonymous_id scheme, untouched. Logging in grants nothing by itself:
# a user becomes a moderator only when an admin adds them to the MODERATORS_GROUP_NAME group
# (see docs/features/moderation.md for the one-time setup). With no credentials configured
# (e.g. dev), the provider app is simply not installed: /accounts/discord/login/ 404s, the
# whoami endpoint reports discordEnabled=false, and nothing crashes.
DISCORD_CLIENT_ID = env("DISCORD_CLIENT_ID", default="")
DISCORD_CLIENT_SECRET = env("DISCORD_CLIENT_SECRET", default="")
DISCORD_AUTH_ENABLED = bool(DISCORD_CLIENT_ID and DISCORD_CLIENT_SECRET)
if DISCORD_AUTH_ENABLED:
    INSTALLED_APPS.append("allauth.socialaccount.providers.discord")
    # App-in-settings configuration - no SocialApp DB row (and no django.contrib.sites) needed.
    SOCIALACCOUNT_PROVIDERS = {"discord": {"APPS": [{"client_id": DISCORD_CLIENT_ID, "secret": DISCORD_CLIENT_SECRET}]}}
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Django admin login, unchanged
    "allauth.account.auth_backends.AuthenticationBackend",
]
ACCOUNT_EMAIL_VERIFICATION = "none"  # Discord is the identity authority; no verification emails
SOCIALACCOUNT_AUTO_SIGNUP = True  # first Discord login auto-creates the Django user
# Skip allauth's confirmation interstitial and go straight to the Discord redirect on GET.
# Tradeoff (read from allauth's own source, socialaccount/providers/base/views.py +
# base/utils.py): that interstitial exists as a login-CSRF guard - it's checked BEFORE any
# OAuth session state is written, so without it a bare cross-site GET (<img src>, hidden
# iframe, plain link) to this login URL immediately writes session state and redirects to
# Discord with no same-site interaction required. Combined with AUTO_SIGNUP=True above, if
# the victim's browser already holds a live, previously-authorized Discord session for this
# app, that forced flow can complete silently on both sides. The ceiling on that is still low
# for this app: Discord identity resolution isn't attacker-controlled, so the worst case is a
# surprising silent login into the victim's OWN correctly-identified account - not the classic
# login-CSRF account-substitution attack where an attacker's account ends up with the
# victim's data. Skipping the interstitial is the near-universal convention for "Sign in with
# X" buttons (the button click on OUR page is already the user's confirmation); one extra
# click after that adds friction without closing a realistic gap for a zero-knowledge app with
# no attacker-controlled account identity. Same category of call already made for logout
# below (docs/features/moderation.md).
SOCIALACCOUNT_LOGIN_ON_GET = True
# Logout via a plain link so it can round-trip back to the frontend with ?next=. The tradeoff
# (a hostile page could force-logout a moderator - a nuisance, not an escalation) is documented
# in docs/features/moderation.md.
ACCOUNT_LOGOUT_ON_GET = True
# Allows ?next= redirects back to the frontend origin - see accounts.adapter.
ACCOUNT_ADAPTER = "accounts.adapter.FrontendRedirectAccountAdapter"
# The Django auth group whose members count as moderators (see cardpicker.moderation). A
# setting rather than a hardcoded string so a future grant mechanism (e.g. syncing membership
# from a Discord guild role) only has to manage this one group.
MODERATORS_GROUP_NAME = env("MODERATORS_GROUP_NAME", default="Moderators")

# The moderator session cookie must round-trip from the cross-site frontend origin
# (github.io <-> api.proxyprints.ca), which requires SameSite=None + Secure in production -
# set via env there. Defaults suit local dev: localhost:3000 -> localhost:8000 is same-site,
# so Lax cookies flow over plain http.
SESSION_COOKIE_SAMESITE = env("SESSION_COOKIE_SAMESITE", default="Lax")
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)
# Lets browsers attach credentials (the session cookie) to CORS requests from the explicit
# allowlist above. Only fetches that opt in with credentials:'include' are affected;
# anonymous traffic is byte-identical.
CORS_ALLOW_CREDENTIALS = env.bool("CORS_ALLOW_CREDENTIALS", default=True)

ROOT_URLCONF = "MPCAutofill.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "MPCAutofill.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": env("DATABASE_ENGINE", default="django.db.backends.postgresql"),
        "NAME": env("DATABASE_NAME", default="mpcautofill"),
        "USER": env("DATABASE_USER", default="mpcautofill"),
        "PASSWORD": env("DATABASE_PASSWORD", default="mpcautofill"),
        "HOST": env("DATABASE_HOST", default="localhost"),
        "PORT": env("DATABASE_PORT", default=5432),
    }
}
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Caches
# https://docs.djangoproject.com/en/4.2/topics/cache/
#
# ---------------------------------------------------------------------------
# WHICH CACHE DO I USE?  (read this before adding a `cache.get`/`cache.set`)
# ---------------------------------------------------------------------------
# * Written and read WITHIN ONE REQUEST PATH (compute-on-miss inside the same
#   view, per-process rate-limit counters, memoised work that is cheap to
#   redo) -> `default`. Fast, no database round trip.
#
# * Written in ONE PROCESS and read in ANOTHER (a cron-invoked management
#   command that warms a blob for the web tier; a django-q task whose output
#   an endpoint serves; anything at all where the writer is not the process
#   that answers the request) -> `caches["shared"]`, named explicitly:
#
#       from django.core.cache import caches
#       caches["shared"].set("my-blob-v1", payload, 3600)
#
#   `default` is `LocMemCache`, which is a per-process dict. A management
#   command populates its OWN process's memory and exits; the gunicorn
#   process serving requests never observes the write, so a "cron warms,
#   endpoint reads cache-only" design misses 100% of the time while both
#   ends report success. That is issue #538. Reaching for `default` from a
#   management command is the bug; `caches["shared"]` is the fix.
#
# WHY `default` IS STILL LocMemCache (do not "simplify" this to one entry):
#
# * `django_ratelimit` (imported in `cardpicker/views.py`) uses the DEFAULT
#   cache, because no `RATELIMIT_*` setting redirects it. Moving it onto a
#   database cache would make every rate-limited request a database read plus
#   a write - i.e. it would add load through the very mechanism that exists
#   to shed load.
#
# * `cardpicker/review_clusters.py` caches a `list[ReviewCluster]` built over
#   a ~135,000-row review queue. On a database cache every read of that is a
#   pickle round trip through Postgres.
#
# Neither of those is incorrect today (both write and read inside a single
# gunicorn worker - `docker/django/Dockerfile`'s CMD passes no `--workers`),
# so neither needs to move. Making `default` itself shared is the separate,
# larger change that must land before that CMD can ever gain `--workers`;
# see issue #538. Do not do it as a drive-by here.
# ---------------------------------------------------------------------------

# Table backing the "shared" cache. The migration that creates it
# (`cardpicker/migrations/0092_shared_cache_table.py`) hardcodes this same
# literal, deliberately - a migration must not read mutable settings. The two
# are pinned together by a test (`cardpicker/tests/test_shared_cache.py`).
SHARED_CACHE_TABLE = "shared_cache"

CACHES = {
    # Written out explicitly rather than left implicit. This is exactly what
    # Django falls back to when `CACHES` is absent, so behaviour is unchanged.
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "",  # Django's own default for an unnamed LocMemCache.
    },
    # Cross-process cache. Backed by a table on the existing Postgres, so it
    # needs no new service in the compose stack and it is created by `migrate`
    # (which `docker/django/entrypoint.sh` already runs) rather than by an
    # operator remembering to run `createcachetable` by hand.
    "shared": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": SHARED_CACHE_TABLE,
        "OPTIONS": {
            # Stated, not inherited. Django's default is 300 entries; the
            # expected load here is a handful of warmed blobs, so 1000 is
            # ~100x headroom and culling should never fire. That matters
            # because a silent cull of a warmed blob presents exactly like
            # the bug this cache exists to fix: the endpoint misses, the
            # warmer reports success, and nothing logs anything.
            "MAX_ENTRIES": 1000,
            # Cull 1/3 of entries if MAX_ENTRIES is ever reached - Django's
            # default ratio, restated so it is a decision rather than an
            # inheritance. Explicitly NOT 0, which would flush the entire
            # table in one statement.
            "CULL_FREQUENCY": 3,
        },
        # Django's default, restated. Writers should pass an explicit TTL
        # anyway (`caches["shared"].set(key, value, 3600)`); a warmer that
        # forgets gets a 5-minute entry and finds out quickly, which is the
        # preferable failure over a stale blob that never expires.
        "TIMEOUT": 300,
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = env("LANG_CODE", default="en-us")

TIME_ZONE = env("TIME_ZONE", default="America/New_York")

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_URL = "/" + env("STATIC", default="static") + "/"
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

STATICFILES_DIRS = [
    os.path.normpath(os.path.join(BASE_DIR, "cardpicker/static")),
]

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), env("STATIC", default="static"))

# elasticsearch DSL settings
ELASTICSEARCH_HOST = env("ELASTICSEARCH_HOST", default="localhost")
ELASTICSEARCH_PORT = env("ELASTICSEARCH_PORT", default="9200")
ELASTICSEARCH_DSL = {
    "default": {"hosts": f"{ELASTICSEARCH_HOST}:{ELASTICSEARCH_PORT}"},
}

ELASTICSEARCH_DSL_AUTOSYNC = False

# The Cloudflare Worker image CDN (image-cdn/, docs/features/image-cdn.md) - the frontend
# reads this as a build-time NEXT_PUBLIC_ var, so the backend has never needed its own copy
# until now: cardpicker.local_identify_printing_tags (docs/features/printing-tags.md's Stage 8)
# fetches a card's own full-resolution image server-side for OCR/phash, via the same Worker's
# "full" tier the PDF export path already relies on for print-quality output (Google Drive
# sources only today - see get_worker_image_url in that module).
IMAGE_WORKER_URL = env("IMAGE_WORKER_URL", default="https://cdn.proxyprints.ca")

# OCR engine seam (issue #423, cardpicker/local_ocr.py's own module docstring): "pytesseract"
# (the OLD default, unchanged process-per-call behavior) or "tesserocr" (persistent in-process
# binding, ~5.7x faster per the 2026-07-25 spike - see that module's docstring for why the swap
# is real output drift, not a transparent speed-up).
#
# THE FLIP (issue #480's combined whole-catalog pass, gated on this PR's own owner A/B GO - see
# this PR's own description, NOT a standalone decision): default now "tesserocr". Bundled with
# this default flip, in the SAME PR: the OCR-derived extractor-version bump in image_evidence.py
# (COLLECTOR_LINE_OCR/ARTIST_OCR/COLLECTOR_LINE_TSV/LEGAL_LINE_EXTRACTOR_VERSION, v1 -> v2 - see
# that module's own comments for the per-extractor reasoning) - per issue #480's correction
# comment, an engine swap WITHOUT a version bump is forbidden (untracked drift under one
# provenance label). `OCR_ENGINE=pytesseract` in the environment is the instant rollback - set it
# to revert every deployed process to the old engine without a code change or redeploy of this
# file, should the post-flip whole-catalog pass need to be paused/reverted.
OCR_ENGINE = env("OCR_ENGINE", default="tesserocr")

# Email for logging
ADMINS = [("admin", env("TARGET_EMAIL", default=""))]
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = env("DJANGO_GMAIL", default="")
EMAIL_HOST_PASSWORD = env("DJANGO_GMAIL_PASSWORD", default="")
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "default from email"

# Logging - closes a real gap found 2026-07-17 diagnosing a live incident (turned out to be a
# 429, not a 500 - nginx's access log ended up being the actual evidence, not django's). Every
# view in cardpicker.views IS already wrapped in ErrorWrappers.to_json, whose own bare
# `except Exception: logger.exception(...)` was, verified empirically, already visible via
# Python's logging.lastResort fallback (stderr, which docker logs captures) even before this
# change - so this isn't "every exception was invisible." What WAS invisible: anything escaping
# that decorator entirely (middleware, ASGI/WSGI-level errors, a future view that forgets the
# decorator) - those route through Django's own exception-to-response machinery, which logs to
# django.request, wired by Django's own DEFAULT_LOGGING to mail_admins ONLY when DEBUG=False,
# never console. console here is additive, not a replacement - mail_admins/ADMINS above stays
# wired as a second channel.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
        "mail_admins": {"class": "django.utils.log.AdminEmailHandler", "level": "ERROR"},
    },
    "loggers": {
        "django.request": {
            "handlers": ["console", "mail_admins"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# Database update settings
DEFAULT_CARDBACK_FOLDER_PATH = env("DEFAULT_CARDBACK_FOLDER_PATH", default="Chilli_Axe's MTG Renders / 12. Cardbacks")
DEFAULT_CARDBACK_IMAGE_NAME = env("DEFAULT_CARDBACK_IMAGE_NAME", default="Black Lotus")

# Game integration - see integrations.py for valid options
GAME = env("GAME", default="")

# PATREON
PATREON_ACCESS = env("PATREON_ACCESS", default="")
PATREON_REFRESH = env("PATREON_REFRESH", default="")
PATREON_CLIENT = env("PATREON_CLIENT", default="")
PATREON_SECRET = env("PATREON_SECRET", default="")
PATREON_URL = env("PATREON_URL", default="")

# django-q2
Q_CLUSTER = {
    "name": "DjangoORM",
    "workers": 8,
    "recycle": 500,
    "timeout": 60 * 60 * 12,  # 12 hours - extreme upper limit
    "retry": 60 * 60 * 12 + 1,  # must be longer than timeout
    "max_attempts": 1,
    "compress": True,
    "save_limit": 250,
    "queue_limit": 500,
    "cpu_affinity": 1,
    "label": "Django Q2",
    "orm": "default",
}

# Stage E Phase 2 - streaming dispatch loop (docs/proposals/stage-e-streaming.md §3, docs/features/
# stage-e-operations.md's "Phase 2" section). Default OFF, exactly matching this phase's own
# NOT-IN-SCOPE line ("actually enabling the trigger in prod settings ... turning it on is the
# phase-3 shakedown's polled owner action") - the event-driven card-create/evidence-change signal
# receivers (cardpicker/stage_e_signals.py) and the cron backstop sweep
# (management/commands/stream_backstop_sweep.py) are both wired unconditionally, but every one of
# them checks this flag first and is a no-op while it's False. Flipping it to True is the ONLY
# action phase 3 needs to take to go live - no redeploy of this module required.
STAGE_E_STREAMING_ENABLED = env.bool("STAGE_E_STREAMING_ENABLED", default=False)

# Stage C evidence transfer kill-switch (issue #473 PR-2, Tron §8 gate condition, 2026-07-25) -
# cardpicker/evidence_transfer.py's own module docstring has the full mechanism writeup. Default
# `True` (transfer is ON by default for this first pass) so the feature actually runs without an
# operator having to flip it on first - `False` makes `find_transfer_source` return `None`
# unconditionally (no query issued), so both call sites (`stage_e_dispatch._run_stage_c`,
# `run_image_evidence_cohort._fetch_one_card`) fall straight through to their own pre-existing
# real-fetch path, exactly as if this feature didn't exist. Exists for first-pass reversibility -
# a single settings flip isolates whether a live-run anomaly originates in transfer, no code change
# or redeploy needed.
STAGE_C_EVIDENCE_TRANSFER_ENABLED = env.bool("STAGE_C_EVIDENCE_TRANSFER_ENABLED", default=True)

# Micro-batch size OVERRIDE - `None` (the default) means AUTOSCALE (2026-07-29, owner directive
# "regarding batch size we have to follow the data. i want it to scale with available hardware up
# to the fetch saturation limit while keeping the mem overhead low and fastest bulk timing").
# `cardpicker/stage_e_batch_sizing.py`'s own module docstring carries the whole rule, the
# measurement table it was read off, and the precedence order; nothing about the decision lives
# here any more.
#
# The §10(c) placeholder this used to hold (a mid-range 25, explicitly "not a considered answer"
# pending the shakedown's own measurement) is now RETIRED: that measurement exists, and its answer
# is not a constant. What survives is the reason the placeholder was env-tunable in the first
# place - an operator must be able to pin a size without a code change - so a non-`None` value
# here still outranks the rule entirely. It is now genuinely an OVERRIDE rather than the default
# path, which is why it defaults to `None` instead of a number: with a number here there is no way
# for the rule to tell "an operator chose 25" apart from "nobody has chosen anything".
#
# DEPLOYMENT NOTE: an environment that exports `STAGE_E_MICRO_BATCH_SIZE` at all (the deployed
# container currently exports `25`) is PINNED and will not autoscale. Unset the variable to let
# the rule run.
STAGE_E_MICRO_BATCH_SIZE = env.int("STAGE_E_MICRO_BATCH_SIZE", default=None)

# Streaming concurrency cap (companion to the 2026-07-24 shakedown's vote-collision fix, PR #448 -
# see cardpicker/stage_e_concurrency.py's own module docstring for the full incident/mechanism
# writeup). Caps the number of CONCURRENTLY-EXECUTING dispatch_micro_batch calls across every
# django-q2 worker PROCESS (Q_CLUSTER["workers"] = 8 above) to this value - the shakedown's first
# live run had eight concurrent dispatches, each running CPU-bound OCR/phash extraction, trip the
# host-load envelope bar on a host with only 7 usable compute cores (docs/features/catalog-
# completion-plan.md L1794/2248/2366's hardware profile). Default 2 is a conservative starting
# point (well under the 7-core ceiling even accounting for other concurrent host activity - Stage
# C's own bulk driver, image-cdn fetch threads, etc.), not a measured/considered answer - tunable
# without a code change (env var) pending real shakedown data, matching STAGE_E_MICRO_BATCH_SIZE's
# own "placeholder, not invented precision" convention immediately above.
STAGE_E_MAX_CONCURRENT_DISPATCHES = env.int("STAGE_E_MAX_CONCURRENT_DISPATCHES", default=2)

# Host-load soft brake (2026-08-05 - cardpicker/stage_e_load_brake.py's own module docstring
# carries the full mechanism). Delays a dispatch,
# never bypasses the hard ceiling: `STAGE_E_HOST_LOAD_SOFT_CEILING` opens the band below
# `operating_envelope.HOST_LOAD_CEILING` (7.0) in which a dispatch sleeps and re-samples instead
# of proceeding straight to the envelope check that would otherwise trip it. All three default to
# values that make the brake active out of the box - matching STAGE_E_MAX_CONCURRENT_DISPATCHES's
# own "safe by default, no opt-in required" convention above, since an instance maintainer running
# their own catalogue for the first time cannot know to enable a knob they don't know exists.
#
# STAGE_E_HOST_LOAD_SOFT_CEILING - ~85% of the hard 7.0 ceiling, read off the two load-average
# trips this brake exists to prevent (7.0796 and 7.17236328125 - both trips were already inside
# 15% of the bar when the pass that produced them was launched, well above this 6.0 line).
STAGE_E_HOST_LOAD_SOFT_CEILING = env.float("STAGE_E_HOST_LOAD_SOFT_CEILING", default=6.0)

# STAGE_E_LOAD_BRAKE_INTERVAL_S - base sleep per brake iteration, before jitter
# (`stage_e_load_brake.run_load_brake`'s own `uniform(0.75, 1.5)` multiplier). 15s is short
# relative to the 1-minute load average it re-samples on each wake so the loop still notices a
# quick recovery, without being so short that a sustained band spends most of its time waking up
# rather than waiting.
STAGE_E_LOAD_BRAKE_INTERVAL_S = env.float("STAGE_E_LOAD_BRAKE_INTERVAL_S", default=15.0)

# STAGE_E_LOAD_BRAKE_MAX_WAIT_S - the absolute bound on how long one dispatch call may spend
# braking before proceeding anyway. `os.getloadavg()`'s one-minute figure is an EWMA with a ~60s
# time constant, so 240s is ~4 time constants (~98% decay of a step change) - long enough for the
# brake to be more than a token gesture, short enough that a sustained real breach still reaches
# the envelope's own hard trip within one dispatch call rather than stalling indefinitely.
STAGE_E_LOAD_BRAKE_MAX_WAIT_S = env.float("STAGE_E_LOAD_BRAKE_MAX_WAIT_S", default=240.0)

# Persistent sweep cursor sizing (issue #458 - see cardpicker/stage_e_dispatch.py's
# `_select_micro_batch` and docs/features/stage-e-operations.md's Phase 2 section for the full
# design). Plain constants, not env-tunable (unlike STAGE_E_MICRO_BATCH_SIZE/
# STAGE_E_MAX_CONCURRENT_DISPATCHES above) - the spec that ratified these two numbers explicitly
# calls for `getattr(settings, ...)` reads with no env passthrough, since these bound a single
# dispatch's own query cost rather than tuning throughput against live shakedown data.
#
# STAGE_E_SELECTION_CHUNK_SIZE - how many candidate pks a single CAS-claimed range covers per
# verification query (`Card.objects.filter(pk__gt=position).order_by("pk")[:CHUNK_SIZE]`, then one
# bounded `ImageEvidence.objects.filter(card_id__in=chunk, ...)` query against exactly that chunk).
STAGE_E_SELECTION_CHUNK_SIZE = 250

# STAGE_E_SELECTION_SCAN_CAP - the total number of candidate pks a single `_select_micro_batch`
# call will examine across however many chunks it takes, even if the batch never fills (a
# mostly-already-processed range can require examining many chunks to find few - or zero -
# eligible cards) - the bound that keeps one dispatch's own selection cost flat regardless of how
# sparse the remaining backlog is.
STAGE_E_SELECTION_SCAN_CAP = 1000

# warm_catalog_stats sweep gate (owner ruling 2026-07-29 - see that command's own module
# docstring for the full skip/staleness mechanism, and docs/features/catalog-stats.md's "Sweep
# gate" section for the accepted up-to-~7h-stale trade this creates).
#
# WARM_CATALOG_STATS_SWEEP_GATE_ENABLED - master switch. Default True: a catalog sweep
# (PilotRunLedger status=RUNNING) genuinely does contend for the same database this warm run's
# five aggregates query, so gating is the safe default everywhere. Settings-driven (not a plain
# constant), same convention as STAGE_E_STREAMING_ENABLED above, so a self-hoster who doesn't run
# sweeps at all - and therefore never wants the warm skipped over a ledger row it doesn't
# understand - can turn the gate off with one env var and no code change or redeploy.
WARM_CATALOG_STATS_SWEEP_GATE_ENABLED = env.bool("WARM_CATALOG_STATS_SWEEP_GATE_ENABLED", default=False)

# WARM_CATALOG_STATS_SWEEP_STALE_AFTER_HOURS - how old a RUNNING PilotRunLedger row has to be
# before the gate stops trusting it and lets the warm run anyway (the guard against a crashed
# sweep that never reached COMPLETED/FAILED permanently freezing the stats page). A full-catalog
# pass measures at ~7.0h as a FLOOR (harvest_fetch_limiter.GOOGLE_IMAGE's own max_concurrency=6 is
# the binding limiter - see docs/features/catalog-completion-plan.md's concurrency-probe section
# for the underlying measurement), so this default is set comfortably above that floor - not a
# tuned-to-the-edge number, deliberately: too tight risks treating a slow-but-live sweep as stale
# and warming stats out from under it; too loose just delays the crash-recovery this guard exists
# for, which is the lesser failure mode of the two (a stale row still self-heals, at worst, at the
# next scheduled sweep). 12h is a little under 2x the measured 7.0h floor - real margin against a
# sweep simply running slower than measured, without leaving a crashed row live for anywhere near
# as long as the next sweep's own cadence would take to overwrite it. Settings-driven for the same
# reason as the gate itself above: tunable without a migration or a code change.
WARM_CATALOG_STATS_SWEEP_STALE_AFTER_HOURS = env.float("WARM_CATALOG_STATS_SWEEP_STALE_AFTER_HOURS", default=12.0)
